# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Thu Jun  5 10:12:49 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_reco_mainwin(object):
    def setupUi(self, reco_mainwin):
        reco_mainwin.setObjectName("reco_mainwin")
        reco_mainwin.resize(1256, 945)
        self.centralwidget = QtGui.QWidget(reco_mainwin)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 301, 521))
        self.groupBox_3.setObjectName("groupBox_3")
        self.inputdirectory = QtGui.QLineEdit(self.groupBox_3)
        self.inputdirectory.setGeometry(QtCore.QRect(10, 50, 251, 27))
        self.inputdirectory.setObjectName("inputdirectory")
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 231, 17))
        self.label_10.setObjectName("label_10")
        self.setinputdirectory = QtGui.QToolButton(self.groupBox_3)
        self.setinputdirectory.setGeometry(QtCore.QRect(260, 50, 30, 26))
        self.setinputdirectory.setObjectName("setinputdirectory")
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 101, 17))
        self.label_3.setObjectName("label_3")
        self.inputtype = QtGui.QComboBox(self.groupBox_3)
        self.inputtype.setGeometry(QtCore.QRect(140, 80, 151, 27))
        self.inputtype.setObjectName("inputtype")
        self.inputtype.addItem("")
        self.inputtype.addItem("")
        self.inputtype.addItem("")
        self.inputtype.addItem("")
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 120, 81, 17))
        self.label.setObjectName("label")
        self.prefix = QtGui.QLineEdit(self.groupBox_3)
        self.prefix.setGeometry(QtCore.QRect(90, 120, 201, 27))
        self.prefix.setObjectName("prefix")
        self.line_4 = QtGui.QFrame(self.groupBox_3)
        self.line_4.setGeometry(QtCore.QRect(10, 150, 281, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 170, 281, 20))
        self.label_11.setObjectName("label_11")
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 190, 281, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.flats = QtGui.QLineEdit(self.gridLayoutWidget)
        self.flats.setObjectName("flats")
        self.gridLayout.addWidget(self.flats, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 2, 1, 1)
        self.interflats = QtGui.QLineEdit(self.gridLayoutWidget)
        self.interflats.setObjectName("interflats")
        self.gridLayout.addWidget(self.interflats, 1, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.raws = QtGui.QLineEdit(self.gridLayoutWidget)
        self.raws.setObjectName("raws")
        self.gridLayout.addWidget(self.raws, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 2, 1, 1)
        self.darks = QtGui.QLineEdit(self.gridLayoutWidget)
        self.darks.setObjectName("darks")
        self.gridLayout.addWidget(self.darks, 0, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 2, 0, 1, 2)
        self.flatfreq = QtGui.QLineEdit(self.gridLayoutWidget)
        self.flatfreq.setObjectName("flatfreq")
        self.gridLayout.addWidget(self.flatfreq, 2, 2, 1, 1)
        self.line_5 = QtGui.QFrame(self.groupBox_3)
        self.line_5.setGeometry(QtCore.QRect(10, 280, 281, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 300, 291, 213))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 3, 2, 1, 1)
        self.binsize = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.binsize.setObjectName("binsize")
        self.gridLayout_3.addWidget(self.binsize, 6, 3, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 4, 2, 1, 1)
        self.roi_right = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.roi_right.setObjectName("roi_right")
        self.gridLayout_3.addWidget(self.roi_right, 3, 3, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 4, 0, 1, 1)
        self.roi_lower = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.roi_lower.setObjectName("roi_lower")
        self.gridLayout_3.addWidget(self.roi_lower, 4, 3, 1, 1)
        self.label_33 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 6, 0, 1, 3)
        self.roi_upper = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.roi_upper.setObjectName("roi_upper")
        self.gridLayout_3.addWidget(self.roi_upper, 4, 1, 1, 1)
        self.line_19 = QtGui.QFrame(self.gridLayoutWidget_3)
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout_3.addWidget(self.line_19, 7, 0, 1, 4)
        self.roion = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.roion.setObjectName("roion")
        self.gridLayout_3.addWidget(self.roion, 2, 0, 1, 4)
        self.roi_left = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.roi_left.setObjectName("roi_left")
        self.gridLayout_3.addWidget(self.roi_left, 3, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 3, 0, 1, 1)
        self.line_12 = QtGui.QFrame(self.gridLayoutWidget_3)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_3.addWidget(self.line_12, 1, 0, 1, 4)
        self.preflatsonly = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.preflatsonly.setObjectName("preflatsonly")
        self.gridLayout_3.addWidget(self.preflatsonly, 0, 0, 1, 4)
        self.line_18 = QtGui.QFrame(self.gridLayoutWidget_3)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_3.addWidget(self.line_18, 5, 0, 1, 4)
        self.label_34 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 8, 0, 1, 3)
        self.scaleimagefactor = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.scaleimagefactor.setObjectName("scaleimagefactor")
        self.gridLayout_3.addWidget(self.scaleimagefactor, 8, 3, 1, 1)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(320, 210, 611, 611))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ImgViewer = QtGui.QLabel(self.frame)
        self.ImgViewer.setGeometry(QtCore.QRect(0, 0, 611, 611))
        self.ImgViewer.setObjectName("ImgViewer")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(410, 0, 441, 23))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 0, 1, 1)
        self.afsaccount = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.afsaccount.setObjectName("afsaccount")
        self.gridLayout_2.addWidget(self.afsaccount, 0, 1, 1, 1)
        self.cons2 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.cons2.setObjectName("cons2")
        self.gridLayout_2.addWidget(self.cons2, 0, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 540, 301, 271))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_6 = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 30, 281, 221))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.setfltpdirectory = QtGui.QToolButton(self.gridLayoutWidget_6)
        self.setfltpdirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.setfltpdirectory.setObjectName("setfltpdirectory")
        self.gridLayout_6.addWidget(self.setfltpdirectory, 3, 1, 1, 1)
        self.sinograms = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.sinograms.setMinimumSize(QtCore.QSize(0, 26))
        self.sinograms.setObjectName("sinograms")
        self.gridLayout_6.addWidget(self.sinograms, 6, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.setcprdirectory = QtGui.QToolButton(self.gridLayoutWidget_6)
        self.setcprdirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.setcprdirectory.setObjectName("setcprdirectory")
        self.gridLayout_6.addWidget(self.setcprdirectory, 1, 1, 1, 1)
        self.sinogramdirectory = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.sinogramdirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.sinogramdirectory.setObjectName("sinogramdirectory")
        self.gridLayout_6.addWidget(self.sinogramdirectory, 5, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 2, 0, 1, 1)
        self.cprdirectory = QtGui.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cprdirectory.sizePolicy().hasHeightForWidth())
        self.cprdirectory.setSizePolicy(sizePolicy)
        self.cprdirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.cprdirectory.setObjectName("cprdirectory")
        self.gridLayout_6.addWidget(self.cprdirectory, 1, 0, 1, 1)
        self.label_43 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_43.setObjectName("label_43")
        self.gridLayout_6.addWidget(self.label_43, 7, 0, 1, 1)
        self.setsinogramdirectory = QtGui.QToolButton(self.gridLayoutWidget_6)
        self.setsinogramdirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.setsinogramdirectory.setObjectName("setsinogramdirectory")
        self.gridLayout_6.addWidget(self.setsinogramdirectory, 5, 1, 1, 1)
        self.fltpdirectory = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.fltpdirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.fltpdirectory.setObjectName("fltpdirectory")
        self.gridLayout_6.addWidget(self.fltpdirectory, 3, 0, 1, 1)
        self.recodirectory = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.recodirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.recodirectory.setObjectName("recodirectory")
        self.gridLayout_6.addWidget(self.recodirectory, 8, 0, 1, 1)
        self.setrecodirectory = QtGui.QToolButton(self.gridLayoutWidget_6)
        self.setrecodirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.setrecodirectory.setObjectName("setrecodirectory")
        self.gridLayout_6.addWidget(self.setrecodirectory, 8, 1, 1, 1)
        self.gridLayout_6.setRowMinimumHeight(6, 30)
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(320, 20, 301, 171))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget_4 = QtGui.QWidget(self.groupBox_5)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 281, 131))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 0, 3, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 0, 0, 1, 1)
        self.pag_delta = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.pag_delta.setObjectName("pag_delta")
        self.gridLayout_4.addWidget(self.pag_delta, 1, 1, 1, 2)
        self.pag_energy = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.pag_energy.setObjectName("pag_energy")
        self.gridLayout_4.addWidget(self.pag_energy, 0, 1, 1, 2)
        self.pag_pxsize = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.pag_pxsize.setObjectName("pag_pxsize")
        self.gridLayout_4.addWidget(self.pag_pxsize, 0, 4, 1, 1)
        self.label_27 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 1, 3, 1, 1)
        self.pag_beta = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.pag_beta.setObjectName("pag_beta")
        self.gridLayout_4.addWidget(self.pag_beta, 1, 4, 1, 1)
        self.label_28 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 2, 0, 1, 3)
        self.pag_distance = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.pag_distance.setObjectName("pag_distance")
        self.gridLayout_4.addWidget(self.pag_distance, 2, 3, 1, 2)
        self.label_26 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(940, 20, 301, 521))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_7 = QtGui.QWidget(self.groupBox_4)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 30, 281, 480))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.geometry = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.geometry.setObjectName("geometry")
        self.geometry.addItem("")
        self.geometry.addItem("")
        self.geometry.addItem("")
        self.geometry.addItem("")
        self.gridLayout_7.addWidget(self.geometry, 18, 0, 1, 2)
        self.label_40 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 21, 0, 1, 1)
        self.edgepadding = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.edgepadding.setObjectName("edgepadding")
        self.gridLayout_7.addWidget(self.edgepadding, 5, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 5, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 9, 0, 1, 1)
        self.filter = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.filter.setObjectName("filter")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.gridLayout_7.addWidget(self.filter, 0, 1, 1, 1)
        self.line_16 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_7.addWidget(self.line_16, 16, 0, 1, 2)
        self.line_13 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_7.addWidget(self.line_13, 12, 0, 1, 2)
        self.rotationangle = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.rotationangle.setObjectName("rotationangle")
        self.gridLayout_7.addWidget(self.rotationangle, 15, 1, 1, 1)
        self.line_7 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_7.addWidget(self.line_7, 1, 0, 1, 2)
        self.centerofrotation = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.centerofrotation.setObjectName("centerofrotation")
        self.gridLayout_7.addWidget(self.centerofrotation, 7, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 3, 0, 1, 1)
        self.outputtype = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.outputtype.setObjectName("outputtype")
        self.outputtype.addItem("")
        self.outputtype.addItem("")
        self.outputtype.addItem("")
        self.outputtype.addItem("")
        self.outputtype.addItem("")
        self.gridLayout_7.addWidget(self.outputtype, 9, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_32.setObjectName("label_32")
        self.gridLayout_7.addWidget(self.label_32, 17, 0, 1, 1)
        self.label_39 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 7, 0, 1, 1)
        self.line_10 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_7.addWidget(self.line_10, 8, 0, 1, 2)
        self.zingeron = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.zingeron.setObjectName("zingeron")
        self.gridLayout_7.addWidget(self.zingeron, 20, 0, 1, 1)
        self.cutofffrequency = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.cutofffrequency.setObjectName("cutofffrequency")
        self.gridLayout_7.addWidget(self.cutofffrequency, 3, 1, 1, 1)
        self.shiftcorrection = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.shiftcorrection.setObjectName("shiftcorrection")
        self.gridLayout_7.addWidget(self.shiftcorrection, 13, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 15, 0, 1, 1)
        self.line_14 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_7.addWidget(self.line_14, 14, 0, 1, 2)
        self.line_9 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_7.addWidget(self.line_9, 4, 0, 1, 2)
        self.line_21 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout_7.addWidget(self.line_21, 19, 0, 1, 2)
        self.line_11 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_7.addWidget(self.line_11, 6, 0, 1, 2)
        self.label_41 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_41.setMinimumSize(QtCore.QSize(0, 35))
        self.label_41.setWordWrap(True)
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 22, 0, 1, 1)
        self.zinger_thresh = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.zinger_thresh.setObjectName("zinger_thresh")
        self.gridLayout_7.addWidget(self.zinger_thresh, 21, 1, 1, 1)
        self.zinger_width = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.zinger_width.setObjectName("zinger_width")
        self.gridLayout_7.addWidget(self.zinger_width, 22, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 10, 0, 1, 1)
        self.tifmin = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.tifmin.setObjectName("tifmin")
        self.gridLayout_7.addWidget(self.tifmin, 10, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_42.setObjectName("label_42")
        self.gridLayout_7.addWidget(self.label_42, 11, 0, 1, 1)
        self.tifmax = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.tifmax.setObjectName("tifmax")
        self.gridLayout_7.addWidget(self.tifmax, 11, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(630, 20, 301, 191))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.wavelettype = QtGui.QComboBox(self.groupBox_2)
        self.wavelettype.setGeometry(QtCore.QRect(190, 60, 101, 27))
        self.wavelettype.setObjectName("wavelettype")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 131, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 161, 17))
        self.label_6.setObjectName("label_6")
        self.waveletdecompositionlevel = QtGui.QLineEdit(self.groupBox_2)
        self.waveletdecompositionlevel.setGeometry(QtCore.QRect(190, 130, 101, 27))
        self.waveletdecompositionlevel.setObjectName("waveletdecompositionlevel")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 171, 17))
        self.label_7.setObjectName("label_7")
        self.sigmaingaussfilter = QtGui.QLineEdit(self.groupBox_2)
        self.sigmaingaussfilter.setGeometry(QtCore.QRect(190, 160, 101, 27))
        self.sigmaingaussfilter.setObjectName("sigmaingaussfilter")
        self.waveletpaddingmode = QtGui.QComboBox(self.groupBox_2)
        self.waveletpaddingmode.setGeometry(QtCore.QRect(190, 90, 101, 27))
        self.waveletpaddingmode.setObjectName("waveletpaddingmode")
        self.waveletpaddingmode.addItem("")
        self.waveletpaddingmode.addItem("")
        self.waveletpaddingmode.addItem("")
        self.waveletpaddingmode.addItem("")
        self.waveletpaddingmode.addItem("")
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 181, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(40, 20, 251, 41))
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.runringremoval = QtGui.QCheckBox(self.groupBox_2)
        self.runringremoval.setGeometry(QtCore.QRect(10, 30, 21, 23))
        self.runringremoval.setObjectName("runringremoval")
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(940, 540, 301, 281))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayoutWidget_5 = QtGui.QWidget(self.groupBox_6)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 30, 293, 251))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.paganinon = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.paganinon.setObjectName("paganinon")
        self.gridLayout_5.addWidget(self.paganinon, 2, 0, 1, 3)
        self.cpron = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.cpron.setObjectName("cpron")
        self.gridLayout_5.addWidget(self.cpron, 0, 0, 1, 3)
        self.reconstructon = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.reconstructon.setObjectName("reconstructon")
        self.gridLayout_5.addWidget(self.reconstructon, 7, 0, 1, 3)
        self.sinon = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sinon.setObjectName("sinon")
        self.gridLayout_5.addWidget(self.sinon, 4, 0, 1, 3)
        self.steplines = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.steplines.setMinimumSize(QtCore.QSize(0, 27))
        self.steplines.setMaximumSize(QtCore.QSize(50, 16777215))
        self.steplines.setObjectName("steplines")
        self.gridLayout_5.addWidget(self.steplines, 6, 3, 1, 1)
        self.label_36 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 6, 0, 1, 3)
        self.sin_fromcpr = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.sin_fromcpr.setMinimumSize(QtCore.QSize(100, 0))
        self.sin_fromcpr.setObjectName("sin_fromcpr")
        self.gridLayout_5.addWidget(self.sin_fromcpr, 5, 1, 1, 1)
        self.sin_fromfltp = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.sin_fromfltp.setObjectName("sin_fromfltp")
        self.gridLayout_5.addWidget(self.sin_fromfltp, 5, 2, 1, 2)
        self.withlog = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.withlog.setObjectName("withlog")
        self.gridLayout_5.addWidget(self.withlog, 1, 1, 1, 2)
        self.widget = QtGui.QWidget(self.gridLayoutWidget_5)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtGui.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 191, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fltp_fromtif = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.fltp_fromtif.setObjectName("fltp_fromtif")
        self.horizontalLayout.addWidget(self.fltp_fromtif)
        self.fltp_fromcpr = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.fltp_fromcpr.setObjectName("fltp_fromcpr")
        self.horizontalLayout.addWidget(self.fltp_fromcpr)
        self.gridLayout_5.addWidget(self.widget, 3, 1, 1, 3)
        self.sin_fromtif = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.sin_fromtif.setObjectName("sin_fromtif")
        self.gridLayout_5.addWidget(self.sin_fromtif, 5, 0, 1, 1)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 820, 231, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_30 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_2.addWidget(self.label_30)
        self.jobname = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.jobname.setObjectName("jobname")
        self.horizontalLayout_2.addWidget(self.jobname)
        self.gridLayoutWidget_8 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(20, 860, 861, 32))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_9 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.singleslice = QtGui.QPushButton(self.gridLayoutWidget_8)
        self.singleslice.setObjectName("singleslice")
        self.gridLayout_9.addWidget(self.singleslice, 0, 3, 1, 1)
        self.testbutton = QtGui.QPushButton(self.gridLayoutWidget_8)
        self.testbutton.setObjectName("testbutton")
        self.gridLayout_9.addWidget(self.testbutton, 0, 2, 1, 1)
        self.submit = QtGui.QPushButton(self.gridLayoutWidget_8)
        self.submit.setObjectName("submit")
        self.gridLayout_9.addWidget(self.submit, 0, 0, 1, 1)
        self.clearfields = QtGui.QPushButton(self.gridLayoutWidget_8)
        self.clearfields.setObjectName("clearfields")
        self.gridLayout_9.addWidget(self.clearfields, 0, 1, 1, 1)
        self.print_cmd = QtGui.QCheckBox(self.gridLayoutWidget_8)
        self.print_cmd.setObjectName("print_cmd")
        self.gridLayout_9.addWidget(self.print_cmd, 0, 4, 1, 1)
        self.develbranchon = QtGui.QCheckBox(self.gridLayoutWidget_8)
        self.develbranchon.setObjectName("develbranchon")
        self.gridLayout_9.addWidget(self.develbranchon, 0, 5, 1, 1)
        self.openinfiji = QtGui.QCheckBox(self.centralwidget)
        self.openinfiji.setGeometry(QtCore.QRect(320, 820, 281, 23))
        self.openinfiji.setObjectName("openinfiji")
        reco_mainwin.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(reco_mainwin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1256, 23))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        reco_mainwin.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(reco_mainwin)
        self.statusbar.setObjectName("statusbar")
        reco_mainwin.setStatusBar(self.statusbar)
        self.menuloadsettings = QtGui.QAction(reco_mainwin)
        self.menuloadsettings.setObjectName("menuloadsettings")
        self.menusavesettings = QtGui.QAction(reco_mainwin)
        self.menusavesettings.setObjectName("menusavesettings")
        self.exitapp = QtGui.QAction(reco_mainwin)
        self.exitapp.setObjectName("exitapp")
        self.menuMenu.addAction(self.menuloadsettings)
        self.menuMenu.addAction(self.menusavesettings)
        self.menuMenu.addAction(self.exitapp)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(reco_mainwin)
        QtCore.QMetaObject.connectSlotsByName(reco_mainwin)

    def retranslateUi(self, reco_mainwin):
        reco_mainwin.setWindowTitle(QtGui.QApplication.translate("reco_mainwin", "GRecoMan 1.1-beta-26-g797f2ad", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("reco_mainwin", "Input Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("reco_mainwin", "Input directory (TIF folder)", None, QtGui.QApplication.UnicodeUTF8))
        self.setinputdirectory.setText(QtGui.QApplication.translate("reco_mainwin", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("reco_mainwin", "Input type (-I)", None, QtGui.QApplication.UnicodeUTF8))
        self.inputtype.setItemText(0, QtGui.QApplication.translate("reco_mainwin", "DMP", None, QtGui.QApplication.UnicodeUTF8))
        self.inputtype.setItemText(1, QtGui.QApplication.translate("reco_mainwin", "HDF5", None, QtGui.QApplication.UnicodeUTF8))
        self.inputtype.setItemText(2, QtGui.QApplication.translate("reco_mainwin", "TIF", None, QtGui.QApplication.UnicodeUTF8))
        self.inputtype.setItemText(3, QtGui.QApplication.translate("reco_mainwin", "DMP sinos", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("reco_mainwin", "Prefix (-p)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("reco_mainwin", "Scan parameters (-f): Number of images", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("reco_mainwin", "Flats", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("reco_mainwin", "Interflats", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("reco_mainwin", "Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("reco_mainwin", "Darks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("reco_mainwin", "Flat frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("reco_mainwin", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("reco_mainwin", "Lower", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("reco_mainwin", "Upper", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("reco_mainwin", "Binning size (-b)", None, QtGui.QApplication.UnicodeUTF8))
        self.roion.setText(QtGui.QApplication.translate("reco_mainwin", "Region of interest in projection (-r)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("reco_mainwin", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.preflatsonly.setText(QtGui.QApplication.translate("reco_mainwin", "Use only preflats (-u)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("reco_mainwin", "Scale factor of raw img-s (-s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("reco_mainwin", "Application is running on:", None, QtGui.QApplication.UnicodeUTF8))
        self.afsaccount.setText(QtGui.QApplication.translate("reco_mainwin", "AFS-account", None, QtGui.QApplication.UnicodeUTF8))
        self.cons2.setText(QtGui.QApplication.translate("reco_mainwin", "x02da-cons-2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("reco_mainwin", "Output directories", None, QtGui.QApplication.UnicodeUTF8))
        self.setfltpdirectory.setText(QtGui.QApplication.translate("reco_mainwin", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("reco_mainwin", "Corrected projections (CPR-s)", None, QtGui.QApplication.UnicodeUTF8))
        self.setcprdirectory.setText(QtGui.QApplication.translate("reco_mainwin", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("reco_mainwin", "Sinograms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("reco_mainwin", "Filtered projections (FLTP-s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("reco_mainwin", "Reconstructions", None, QtGui.QApplication.UnicodeUTF8))
        self.setsinogramdirectory.setText(QtGui.QApplication.translate("reco_mainwin", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.setrecodirectory.setText(QtGui.QApplication.translate("reco_mainwin", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("reco_mainwin", "Paganin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("reco_mainwin", "Pixel size [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("reco_mainwin", "Energy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("reco_mainwin", "Beta", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("reco_mainwin", "Prop. distance [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("reco_mainwin", "Delta", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("reco_mainwin", "Reconstruction", None, QtGui.QApplication.UnicodeUTF8))
        self.geometry.setToolTip(QtGui.QApplication.translate("reco_mainwin", "If \'none\', then the flag is not set at all.", None, QtGui.QApplication.UnicodeUTF8))
        self.geometry.setItemText(0, QtGui.QApplication.translate("reco_mainwin", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.geometry.setItemText(1, QtGui.QApplication.translate("reco_mainwin", "sampling from 0->pi", None, QtGui.QApplication.UnicodeUTF8))
        self.geometry.setItemText(2, QtGui.QApplication.translate("reco_mainwin", "angles in angles.txt", None, QtGui.QApplication.UnicodeUTF8))
        self.geometry.setItemText(3, QtGui.QApplication.translate("reco_mainwin", "sampling from 0->2pi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("reco_mainwin", "Threshold (-H)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("reco_mainwin", "Edge-padding (-Z)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("reco_mainwin", "Output format (-t)", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setToolTip(QtGui.QApplication.translate("reco_mainwin", "If \'none\', then the flag is not set at all.", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setItemText(0, QtGui.QApplication.translate("reco_mainwin", "schepp", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setItemText(1, QtGui.QApplication.translate("reco_mainwin", "hanning", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setItemText(2, QtGui.QApplication.translate("reco_mainwin", "hamming", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setItemText(3, QtGui.QApplication.translate("reco_mainwin", "ramlak", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setItemText(4, QtGui.QApplication.translate("reco_mainwin", "parzen", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setItemText(5, QtGui.QApplication.translate("reco_mainwin", "lanczos", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setItemText(6, QtGui.QApplication.translate("reco_mainwin", "dpc", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setItemText(7, QtGui.QApplication.translate("reco_mainwin", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("reco_mainwin", "Filter (-F)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("reco_mainwin", "Cutoff frequency (-U) ", None, QtGui.QApplication.UnicodeUTF8))
        self.outputtype.setToolTip(QtGui.QApplication.translate("reco_mainwin", "If \'none\', then the flag is not set at all.", None, QtGui.QApplication.UnicodeUTF8))
        self.outputtype.setItemText(0, QtGui.QApplication.translate("reco_mainwin", "TIF-8bit", None, QtGui.QApplication.UnicodeUTF8))
        self.outputtype.setItemText(1, QtGui.QApplication.translate("reco_mainwin", "DMP", None, QtGui.QApplication.UnicodeUTF8))
        self.outputtype.setItemText(2, QtGui.QApplication.translate("reco_mainwin", "DMP+HDF5", None, QtGui.QApplication.UnicodeUTF8))
        self.outputtype.setItemText(3, QtGui.QApplication.translate("reco_mainwin", "TIF-16bit", None, QtGui.QApplication.UnicodeUTF8))
        self.outputtype.setItemText(4, QtGui.QApplication.translate("reco_mainwin", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("reco_mainwin", "Geometry settings (-G)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("reco_mainwin", "Center of rotation (-c)", None, QtGui.QApplication.UnicodeUTF8))
        self.zingeron.setText(QtGui.QApplication.translate("reco_mainwin", "Zinger removal", None, QtGui.QApplication.UnicodeUTF8))
        self.shiftcorrection.setText(QtGui.QApplication.translate("reco_mainwin", "Correct for shift (-q)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("reco_mainwin", "Rotation angle (-a)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("reco_mainwin", "Width of smoothin kernel (-w)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("reco_mainwin", "Min. value for tif (-n)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("reco_mainwin", "Max. value for tif (-x)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("reco_mainwin", "Ring Removal", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(0, QtGui.QApplication.translate("reco_mainwin", "db1", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(1, QtGui.QApplication.translate("reco_mainwin", "db2", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(2, QtGui.QApplication.translate("reco_mainwin", "db3", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(3, QtGui.QApplication.translate("reco_mainwin", "db4", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(4, QtGui.QApplication.translate("reco_mainwin", "db5", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(5, QtGui.QApplication.translate("reco_mainwin", "db6", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(6, QtGui.QApplication.translate("reco_mainwin", "db7", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(7, QtGui.QApplication.translate("reco_mainwin", "db8", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(8, QtGui.QApplication.translate("reco_mainwin", "db9", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(9, QtGui.QApplication.translate("reco_mainwin", "db10", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(10, QtGui.QApplication.translate("reco_mainwin", "db11", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(11, QtGui.QApplication.translate("reco_mainwin", "db12", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(12, QtGui.QApplication.translate("reco_mainwin", "db13", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(13, QtGui.QApplication.translate("reco_mainwin", "db14", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(14, QtGui.QApplication.translate("reco_mainwin", "db15", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(15, QtGui.QApplication.translate("reco_mainwin", "db16", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(16, QtGui.QApplication.translate("reco_mainwin", "db17", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(17, QtGui.QApplication.translate("reco_mainwin", "db18", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(18, QtGui.QApplication.translate("reco_mainwin", "db19", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(19, QtGui.QApplication.translate("reco_mainwin", "db20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("reco_mainwin", "Wavelettype (-y)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("reco_mainwin", "Decomposition level (-V)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("reco_mainwin", "Sigma in Gauss-filter (-E)", None, QtGui.QApplication.UnicodeUTF8))
        self.waveletpaddingmode.setItemText(0, QtGui.QApplication.translate("reco_mainwin", "zero", None, QtGui.QApplication.UnicodeUTF8))
        self.waveletpaddingmode.setItemText(1, QtGui.QApplication.translate("reco_mainwin", "constant", None, QtGui.QApplication.UnicodeUTF8))
        self.waveletpaddingmode.setItemText(2, QtGui.QApplication.translate("reco_mainwin", "symmetric", None, QtGui.QApplication.UnicodeUTF8))
        self.waveletpaddingmode.setItemText(3, QtGui.QApplication.translate("reco_mainwin", "periodic", None, QtGui.QApplication.UnicodeUTF8))
        self.waveletpaddingmode.setItemText(4, QtGui.QApplication.translate("reco_mainwin", "smooth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("reco_mainwin", "Wavelet padding mode (-M)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("reco_mainwin", "Activate wavelet ring removal", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("reco_mainwin", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.paganinon.setText(QtGui.QApplication.translate("reco_mainwin", "Paganin phase retrieval (fltp)", None, QtGui.QApplication.UnicodeUTF8))
        self.cpron.setText(QtGui.QApplication.translate("reco_mainwin", "Create CPR-s", None, QtGui.QApplication.UnicodeUTF8))
        self.reconstructon.setText(QtGui.QApplication.translate("reco_mainwin", "Do reconstruction (-R)", None, QtGui.QApplication.UnicodeUTF8))
        self.sinon.setText(QtGui.QApplication.translate("reco_mainwin", "Create sinograms (sin)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("reco_mainwin", "Interleave sino creation (-j)", None, QtGui.QApplication.UnicodeUTF8))
        self.sin_fromcpr.setText(QtGui.QApplication.translate("reco_mainwin", "from cpr", None, QtGui.QApplication.UnicodeUTF8))
        self.sin_fromfltp.setText(QtGui.QApplication.translate("reco_mainwin", "from fltp", None, QtGui.QApplication.UnicodeUTF8))
        self.withlog.setText(QtGui.QApplication.translate("reco_mainwin", "with log correction", None, QtGui.QApplication.UnicodeUTF8))
        self.fltp_fromtif.setText(QtGui.QApplication.translate("reco_mainwin", "from TIF", None, QtGui.QApplication.UnicodeUTF8))
        self.fltp_fromcpr.setText(QtGui.QApplication.translate("reco_mainwin", "from cpr", None, QtGui.QApplication.UnicodeUTF8))
        self.sin_fromtif.setText(QtGui.QApplication.translate("reco_mainwin", "from tif", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("reco_mainwin", "Job name:", None, QtGui.QApplication.UnicodeUTF8))
        self.singleslice.setText(QtGui.QApplication.translate("reco_mainwin", "Single slice", None, QtGui.QApplication.UnicodeUTF8))
        self.testbutton.setText(QtGui.QApplication.translate("reco_mainwin", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.submit.setText(QtGui.QApplication.translate("reco_mainwin", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.clearfields.setText(QtGui.QApplication.translate("reco_mainwin", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.print_cmd.setText(QtGui.QApplication.translate("reco_mainwin", "Print command line string (debug)", None, QtGui.QApplication.UnicodeUTF8))
        self.develbranchon.setText(QtGui.QApplication.translate("reco_mainwin", "Use \"devel\" branch", None, QtGui.QApplication.UnicodeUTF8))
        self.openinfiji.setText(QtGui.QApplication.translate("reco_mainwin", "Open preview image in Fiji (externally)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("reco_mainwin", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuloadsettings.setText(QtGui.QApplication.translate("reco_mainwin", "Load Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menusavesettings.setText(QtGui.QApplication.translate("reco_mainwin", "Save settings", None, QtGui.QApplication.UnicodeUTF8))
        self.exitapp.setText(QtGui.QApplication.translate("reco_mainwin", "Exit", None, QtGui.QApplication.UnicodeUTF8))

