# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Tue May 13 23:33:46 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_reco_mainwin(object):
    def setupUi(self, reco_mainwin):
        reco_mainwin.setObjectName(_fromUtf8("reco_mainwin"))
        reco_mainwin.resize(1251, 1014)
        self.centralwidget = QtGui.QWidget(reco_mainwin)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 50, 301, 531))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.inputdirectory = QtGui.QLineEdit(self.groupBox_3)
        self.inputdirectory.setGeometry(QtCore.QRect(10, 50, 251, 27))
        self.inputdirectory.setObjectName(_fromUtf8("inputdirectory"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 231, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.setinputdirectory = QtGui.QToolButton(self.groupBox_3)
        self.setinputdirectory.setGeometry(QtCore.QRect(260, 50, 30, 26))
        self.setinputdirectory.setObjectName(_fromUtf8("setinputdirectory"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 101, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.inputtype = QtGui.QComboBox(self.groupBox_3)
        self.inputtype.setGeometry(QtCore.QRect(140, 80, 151, 27))
        self.inputtype.setObjectName(_fromUtf8("inputtype"))
        self.inputtype.addItem(_fromUtf8(""))
        self.inputtype.addItem(_fromUtf8(""))
        self.inputtype.addItem(_fromUtf8(""))
        self.inputtype.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 120, 81, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.prefix = QtGui.QLineEdit(self.groupBox_3)
        self.prefix.setGeometry(QtCore.QRect(90, 120, 201, 27))
        self.prefix.setObjectName(_fromUtf8("prefix"))
        self.line_4 = QtGui.QFrame(self.groupBox_3)
        self.line_4.setGeometry(QtCore.QRect(10, 150, 281, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 170, 281, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 190, 281, 91))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.flats = QtGui.QLineEdit(self.gridLayoutWidget)
        self.flats.setText(_fromUtf8(""))
        self.flats.setObjectName(_fromUtf8("flats"))
        self.gridLayout.addWidget(self.flats, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 1, 2, 1, 1)
        self.interflats = QtGui.QLineEdit(self.gridLayoutWidget)
        self.interflats.setText(_fromUtf8(""))
        self.interflats.setObjectName(_fromUtf8("interflats"))
        self.gridLayout.addWidget(self.interflats, 1, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.raws = QtGui.QLineEdit(self.gridLayoutWidget)
        self.raws.setObjectName(_fromUtf8("raws"))
        self.gridLayout.addWidget(self.raws, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 0, 2, 1, 1)
        self.darks = QtGui.QLineEdit(self.gridLayoutWidget)
        self.darks.setText(_fromUtf8(""))
        self.darks.setObjectName(_fromUtf8("darks"))
        self.gridLayout.addWidget(self.darks, 0, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 2, 0, 1, 2)
        self.flatfreq = QtGui.QLineEdit(self.gridLayoutWidget)
        self.flatfreq.setText(_fromUtf8(""))
        self.flatfreq.setObjectName(_fromUtf8("flatfreq"))
        self.gridLayout.addWidget(self.flatfreq, 2, 2, 1, 1)
        self.line_5 = QtGui.QFrame(self.groupBox_3)
        self.line_5.setGeometry(QtCore.QRect(10, 280, 281, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 300, 291, 213))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 3, 2, 1, 1)
        self.binsize = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.binsize.setObjectName(_fromUtf8("binsize"))
        self.gridLayout_3.addWidget(self.binsize, 6, 3, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 4, 2, 1, 1)
        self.roi_right = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.roi_right.setObjectName(_fromUtf8("roi_right"))
        self.gridLayout_3.addWidget(self.roi_right, 3, 3, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 4, 0, 1, 1)
        self.roi_lower = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.roi_lower.setObjectName(_fromUtf8("roi_lower"))
        self.gridLayout_3.addWidget(self.roi_lower, 4, 3, 1, 1)
        self.label_33 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_3.addWidget(self.label_33, 6, 0, 1, 3)
        self.roi_upper = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.roi_upper.setObjectName(_fromUtf8("roi_upper"))
        self.gridLayout_3.addWidget(self.roi_upper, 4, 1, 1, 1)
        self.line_19 = QtGui.QFrame(self.gridLayoutWidget_3)
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.gridLayout_3.addWidget(self.line_19, 7, 0, 1, 4)
        self.roion = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.roion.setObjectName(_fromUtf8("roion"))
        self.gridLayout_3.addWidget(self.roion, 2, 0, 1, 4)
        self.roi_left = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.roi_left.setObjectName(_fromUtf8("roi_left"))
        self.gridLayout_3.addWidget(self.roi_left, 3, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 3, 0, 1, 1)
        self.line_12 = QtGui.QFrame(self.gridLayoutWidget_3)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.gridLayout_3.addWidget(self.line_12, 1, 0, 1, 4)
        self.preflatsonly = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.preflatsonly.setObjectName(_fromUtf8("preflatsonly"))
        self.gridLayout_3.addWidget(self.preflatsonly, 0, 0, 1, 4)
        self.line_18 = QtGui.QFrame(self.gridLayoutWidget_3)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.gridLayout_3.addWidget(self.line_18, 5, 0, 1, 4)
        self.label_34 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_3.addWidget(self.label_34, 8, 0, 1, 3)
        self.scaleimagefactor = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.scaleimagefactor.setObjectName(_fromUtf8("scaleimagefactor"))
        self.gridLayout_3.addWidget(self.scaleimagefactor, 8, 3, 1, 1)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(320, 270, 611, 611))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.ImgViewer = QtGui.QLabel(self.frame)
        self.ImgViewer.setGeometry(QtCore.QRect(0, 0, 611, 611))
        self.ImgViewer.setText(_fromUtf8(""))
        self.ImgViewer.setObjectName(_fromUtf8("ImgViewer"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(410, 0, 441, 44))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 0, 0, 1, 1)
        self.afsaccount = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.afsaccount.setObjectName(_fromUtf8("afsaccount"))
        self.gridLayout_2.addWidget(self.afsaccount, 0, 1, 1, 1)
        self.cons2 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.cons2.setObjectName(_fromUtf8("cons2"))
        self.gridLayout_2.addWidget(self.cons2, 0, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 580, 301, 281))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget_6 = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 30, 281, 221))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.toolButton_3 = QtGui.QToolButton(self.gridLayoutWidget_6)
        self.toolButton_3.setMinimumSize(QtCore.QSize(0, 22))
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.gridLayout_6.addWidget(self.toolButton_3, 3, 1, 1, 1)
        self.sinograms = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.sinograms.setMinimumSize(QtCore.QSize(0, 26))
        self.sinograms.setObjectName(_fromUtf8("sinograms"))
        self.gridLayout_6.addWidget(self.sinograms, 6, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.toolButton_2 = QtGui.QToolButton(self.gridLayoutWidget_6)
        self.toolButton_2.setMinimumSize(QtCore.QSize(0, 22))
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.gridLayout_6.addWidget(self.toolButton_2, 1, 1, 1, 1)
        self.sinogramdirectory = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.sinogramdirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.sinogramdirectory.setObjectName(_fromUtf8("sinogramdirectory"))
        self.gridLayout_6.addWidget(self.sinogramdirectory, 5, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_6.addWidget(self.label_29, 2, 0, 1, 1)
        self.cprdirectory = QtGui.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cprdirectory.sizePolicy().hasHeightForWidth())
        self.cprdirectory.setSizePolicy(sizePolicy)
        self.cprdirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.cprdirectory.setObjectName(_fromUtf8("cprdirectory"))
        self.gridLayout_6.addWidget(self.cprdirectory, 1, 0, 1, 1)
        self.label_43 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_6.addWidget(self.label_43, 7, 0, 1, 1)
        self.setsinogramdirectory = QtGui.QToolButton(self.gridLayoutWidget_6)
        self.setsinogramdirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.setsinogramdirectory.setObjectName(_fromUtf8("setsinogramdirectory"))
        self.gridLayout_6.addWidget(self.setsinogramdirectory, 5, 1, 1, 1)
        self.fltpdirectory = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.fltpdirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.fltpdirectory.setObjectName(_fromUtf8("fltpdirectory"))
        self.gridLayout_6.addWidget(self.fltpdirectory, 3, 0, 1, 1)
        self.recodirectory = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.recodirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.recodirectory.setObjectName(_fromUtf8("recodirectory"))
        self.gridLayout_6.addWidget(self.recodirectory, 8, 0, 1, 1)
        self.toolButton_4 = QtGui.QToolButton(self.gridLayoutWidget_6)
        self.toolButton_4.setMinimumSize(QtCore.QSize(0, 22))
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.gridLayout_6.addWidget(self.toolButton_4, 8, 1, 1, 1)
        self.gridLayout_6.setRowMinimumHeight(6, 30)
        self.testbutton = QtGui.QPushButton(self.centralwidget)
        self.testbutton.setGeometry(QtCore.QRect(230, 940, 112, 26))
        self.testbutton.setObjectName(_fromUtf8("testbutton"))
        self.submit = QtGui.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(10, 940, 112, 26))
        self.submit.setObjectName(_fromUtf8("submit"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(320, 50, 301, 171))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.groupBox_5)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 281, 131))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_4.addWidget(self.label_25, 0, 3, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 0, 0, 1, 1)
        self.pag_delta = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.pag_delta.setObjectName(_fromUtf8("pag_delta"))
        self.gridLayout_4.addWidget(self.pag_delta, 1, 1, 1, 2)
        self.pag_energy = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.pag_energy.setObjectName(_fromUtf8("pag_energy"))
        self.gridLayout_4.addWidget(self.pag_energy, 0, 1, 1, 2)
        self.pag_pxsize = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.pag_pxsize.setObjectName(_fromUtf8("pag_pxsize"))
        self.gridLayout_4.addWidget(self.pag_pxsize, 0, 4, 1, 1)
        self.label_27 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_4.addWidget(self.label_27, 1, 3, 1, 1)
        self.pag_beta = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.pag_beta.setObjectName(_fromUtf8("pag_beta"))
        self.gridLayout_4.addWidget(self.pag_beta, 1, 4, 1, 1)
        self.label_28 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_4.addWidget(self.label_28, 2, 0, 1, 3)
        self.pag_distance = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.pag_distance.setObjectName(_fromUtf8("pag_distance"))
        self.gridLayout_4.addWidget(self.pag_distance, 2, 3, 1, 2)
        self.label_26 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_4.addWidget(self.label_26, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(940, 50, 301, 641))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.groupBox_4)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 30, 281, 481))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.geometry = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.geometry.setObjectName(_fromUtf8("geometry"))
        self.geometry.addItem(_fromUtf8(""))
        self.geometry.addItem(_fromUtf8(""))
        self.geometry.addItem(_fromUtf8(""))
        self.geometry.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.geometry, 16, 0, 1, 2)
        self.label_40 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_7.addWidget(self.label_40, 19, 0, 1, 1)
        self.edgepadding = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.edgepadding.setObjectName(_fromUtf8("edgepadding"))
        self.gridLayout_7.addWidget(self.edgepadding, 5, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_7.addWidget(self.label_38, 5, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_7.addWidget(self.label_23, 9, 0, 1, 1)
        self.filter = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.filter.setObjectName(_fromUtf8("filter"))
        self.filter.addItem(_fromUtf8(""))
        self.filter.addItem(_fromUtf8(""))
        self.filter.addItem(_fromUtf8(""))
        self.filter.addItem(_fromUtf8(""))
        self.filter.addItem(_fromUtf8(""))
        self.filter.addItem(_fromUtf8(""))
        self.filter.addItem(_fromUtf8(""))
        self.filter.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.filter, 0, 1, 1, 1)
        self.line_16 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.gridLayout_7.addWidget(self.line_16, 14, 0, 1, 2)
        self.line_13 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.gridLayout_7.addWidget(self.line_13, 10, 0, 1, 2)
        self.rotationangle = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.rotationangle.setObjectName(_fromUtf8("rotationangle"))
        self.gridLayout_7.addWidget(self.rotationangle, 13, 1, 1, 1)
        self.line_7 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_7.addWidget(self.line_7, 1, 0, 1, 2)
        self.centerofrotation = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.centerofrotation.setObjectName(_fromUtf8("centerofrotation"))
        self.gridLayout_7.addWidget(self.centerofrotation, 7, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_7.addWidget(self.label_37, 3, 0, 1, 1)
        self.outputtype = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.outputtype.setObjectName(_fromUtf8("outputtype"))
        self.outputtype.addItem(_fromUtf8(""))
        self.outputtype.addItem(_fromUtf8(""))
        self.outputtype.addItem(_fromUtf8(""))
        self.outputtype.addItem(_fromUtf8(""))
        self.outputtype.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.outputtype, 9, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_7.addWidget(self.label_32, 15, 0, 1, 1)
        self.label_39 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_7.addWidget(self.label_39, 7, 0, 1, 1)
        self.line_10 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.gridLayout_7.addWidget(self.line_10, 8, 0, 1, 2)
        self.zingeron = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.zingeron.setObjectName(_fromUtf8("zingeron"))
        self.gridLayout_7.addWidget(self.zingeron, 18, 0, 1, 1)
        self.cutofffrequency = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.cutofffrequency.setObjectName(_fromUtf8("cutofffrequency"))
        self.gridLayout_7.addWidget(self.cutofffrequency, 3, 1, 1, 1)
        self.shiftcorrection = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.shiftcorrection.setObjectName(_fromUtf8("shiftcorrection"))
        self.gridLayout_7.addWidget(self.shiftcorrection, 11, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_7.addWidget(self.label_31, 13, 0, 1, 1)
        self.line_14 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.gridLayout_7.addWidget(self.line_14, 12, 0, 1, 2)
        self.line_9 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_7.addWidget(self.line_9, 4, 0, 1, 2)
        self.line_21 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.gridLayout_7.addWidget(self.line_21, 17, 0, 1, 2)
        self.line_11 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.gridLayout_7.addWidget(self.line_11, 6, 0, 1, 2)
        self.label_41 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_41.setWordWrap(True)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_7.addWidget(self.label_41, 20, 0, 1, 1)
        self.zinger_thresh = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.zinger_thresh.setObjectName(_fromUtf8("zinger_thresh"))
        self.gridLayout_7.addWidget(self.zinger_thresh, 19, 1, 1, 1)
        self.zinger_width = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.zinger_width.setObjectName(_fromUtf8("zinger_width"))
        self.gridLayout_7.addWidget(self.zinger_width, 20, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(630, 50, 301, 201))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.wavelettype = QtGui.QComboBox(self.groupBox_2)
        self.wavelettype.setGeometry(QtCore.QRect(190, 60, 101, 27))
        self.wavelettype.setObjectName(_fromUtf8("wavelettype"))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.wavelettype.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 131, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 161, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.waveletdecompositionlevel = QtGui.QLineEdit(self.groupBox_2)
        self.waveletdecompositionlevel.setGeometry(QtCore.QRect(190, 130, 101, 27))
        self.waveletdecompositionlevel.setObjectName(_fromUtf8("waveletdecompositionlevel"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 171, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.sigmaingaussfilter = QtGui.QLineEdit(self.groupBox_2)
        self.sigmaingaussfilter.setGeometry(QtCore.QRect(190, 160, 101, 27))
        self.sigmaingaussfilter.setObjectName(_fromUtf8("sigmaingaussfilter"))
        self.waveletpaddingmode = QtGui.QComboBox(self.groupBox_2)
        self.waveletpaddingmode.setGeometry(QtCore.QRect(190, 90, 101, 27))
        self.waveletpaddingmode.setObjectName(_fromUtf8("waveletpaddingmode"))
        self.waveletpaddingmode.addItem(_fromUtf8(""))
        self.waveletpaddingmode.addItem(_fromUtf8(""))
        self.waveletpaddingmode.addItem(_fromUtf8(""))
        self.waveletpaddingmode.addItem(_fromUtf8(""))
        self.waveletpaddingmode.addItem(_fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 181, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(40, 20, 251, 41))
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.runringremoval = QtGui.QCheckBox(self.groupBox_2)
        self.runringremoval.setGeometry(QtCore.QRect(10, 30, 21, 23))
        self.runringremoval.setText(_fromUtf8(""))
        self.runringremoval.setObjectName(_fromUtf8("runringremoval"))
        self.clearfields = QtGui.QPushButton(self.centralwidget)
        self.clearfields.setGeometry(QtCore.QRect(120, 940, 112, 26))
        self.clearfields.setObjectName(_fromUtf8("clearfields"))
        self.singleslice = QtGui.QPushButton(self.centralwidget)
        self.singleslice.setGeometry(QtCore.QRect(340, 940, 112, 26))
        self.singleslice.setObjectName(_fromUtf8("singleslice"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(940, 710, 291, 130))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.paganinon = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.paganinon.setObjectName(_fromUtf8("paganinon"))
        self.gridLayout_5.addWidget(self.paganinon, 1, 0, 1, 2)
        self.cpron = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.cpron.setObjectName(_fromUtf8("cpron"))
        self.gridLayout_5.addWidget(self.cpron, 0, 0, 1, 2)
        self.reconstructon = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.reconstructon.setObjectName(_fromUtf8("reconstructon"))
        self.gridLayout_5.addWidget(self.reconstructon, 4, 0, 1, 2)
        self.sinon = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sinon.setObjectName(_fromUtf8("sinon"))
        self.gridLayout_5.addWidget(self.sinon, 2, 0, 1, 2)
        self.steplines = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.steplines.setMaximumSize(QtCore.QSize(50, 16777215))
        self.steplines.setObjectName(_fromUtf8("steplines"))
        self.gridLayout_5.addWidget(self.steplines, 3, 2, 1, 1)
        self.label_36 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_5.addWidget(self.label_36, 3, 0, 1, 2)
        reco_mainwin.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(reco_mainwin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1251, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuScenarios = QtGui.QMenu(self.menubar)
        self.menuScenarios.setObjectName(_fromUtf8("menuScenarios"))
        reco_mainwin.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(reco_mainwin)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        reco_mainwin.setStatusBar(self.statusbar)
        self.menuloadsettings = QtGui.QAction(reco_mainwin)
        self.menuloadsettings.setObjectName(_fromUtf8("menuloadsettings"))
        self.menusavesettings = QtGui.QAction(reco_mainwin)
        self.menusavesettings.setObjectName(_fromUtf8("menusavesettings"))
        self.exitapp = QtGui.QAction(reco_mainwin)
        self.exitapp.setObjectName(_fromUtf8("exitapp"))
        self.actionCreate_only_CPR = QtGui.QAction(reco_mainwin)
        self.actionCreate_only_CPR.setObjectName(_fromUtf8("actionCreate_only_CPR"))
        self.actionCreate_CPR_FLTP = QtGui.QAction(reco_mainwin)
        self.actionCreate_CPR_FLTP.setObjectName(_fromUtf8("actionCreate_CPR_FLTP"))
        self.actionCreate_CPR_FLTP_sinograms = QtGui.QAction(reco_mainwin)
        self.actionCreate_CPR_FLTP_sinograms.setObjectName(_fromUtf8("actionCreate_CPR_FLTP_sinograms"))
        self.actionDo_everything_CPR_FLTP_Reconstruction = QtGui.QAction(reco_mainwin)
        self.actionDo_everything_CPR_FLTP_Reconstruction.setObjectName(_fromUtf8("actionDo_everything_CPR_FLTP_Reconstruction"))
        self.menuMenu.addAction(self.menuloadsettings)
        self.menuMenu.addAction(self.menusavesettings)
        self.menuMenu.addAction(self.exitapp)
        self.menuScenarios.addAction(self.actionCreate_only_CPR)
        self.menuScenarios.addAction(self.actionCreate_CPR_FLTP)
        self.menuScenarios.addAction(self.actionCreate_CPR_FLTP_sinograms)
        self.menuScenarios.addAction(self.actionDo_everything_CPR_FLTP_Reconstruction)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuScenarios.menuAction())

        self.retranslateUi(reco_mainwin)
        QtCore.QMetaObject.connectSlotsByName(reco_mainwin)

    def retranslateUi(self, reco_mainwin):
        reco_mainwin.setWindowTitle(_translate("reco_mainwin", "GRecoMan", None))
        self.groupBox_3.setTitle(_translate("reco_mainwin", "Input Data", None))
        self.label_10.setText(_translate("reco_mainwin", "Input directory (TIF or FLTP folder)", None))
        self.setinputdirectory.setText(_translate("reco_mainwin", "...", None))
        self.label_3.setText(_translate("reco_mainwin", "Input type (-I)", None))
        self.inputtype.setItemText(0, _translate("reco_mainwin", "DMP", None))
        self.inputtype.setItemText(1, _translate("reco_mainwin", "HDF5", None))
        self.inputtype.setItemText(2, _translate("reco_mainwin", "TIF", None))
        self.inputtype.setItemText(3, _translate("reco_mainwin", "DMP sinos", None))
        self.label.setText(_translate("reco_mainwin", "Prefix (-p)", None))
        self.label_11.setText(_translate("reco_mainwin", "Scan parameters (-f): Number of images", None))
        self.label_12.setText(_translate("reco_mainwin", "Flats", None))
        self.label_13.setText(_translate("reco_mainwin", "Interflats", None))
        self.label_14.setText(_translate("reco_mainwin", "Raw", None))
        self.label_15.setText(_translate("reco_mainwin", "Darks", None))
        self.label_16.setText(_translate("reco_mainwin", "Flat frequency", None))
        self.label_20.setText(_translate("reco_mainwin", "Right", None))
        self.label_22.setText(_translate("reco_mainwin", "Lower", None))
        self.label_21.setText(_translate("reco_mainwin", "Upper", None))
        self.label_33.setText(_translate("reco_mainwin", "Binning size (-b)", None))
        self.roion.setText(_translate("reco_mainwin", "Region of interest in projection (-r)", None))
        self.label_19.setText(_translate("reco_mainwin", "Left", None))
        self.preflatsonly.setText(_translate("reco_mainwin", "Use only preflats (-u)", None))
        self.label_34.setText(_translate("reco_mainwin", "Scale factor of raw img-s (-s)", None))
        self.label_18.setText(_translate("reco_mainwin", "Application is running on:", None))
        self.afsaccount.setText(_translate("reco_mainwin", "AFS-account", None))
        self.cons2.setText(_translate("reco_mainwin", "x02da-cons-2", None))
        self.groupBox.setTitle(_translate("reco_mainwin", "Output directories", None))
        self.toolButton_3.setText(_translate("reco_mainwin", "...", None))
        self.label_4.setText(_translate("reco_mainwin", "Corrected projections (CPR-s)", None))
        self.toolButton_2.setText(_translate("reco_mainwin", "...", None))
        self.label_2.setText(_translate("reco_mainwin", "Sinograms", None))
        self.label_29.setText(_translate("reco_mainwin", "Filtered projections", None))
        self.label_43.setText(_translate("reco_mainwin", "Reconstructions", None))
        self.setsinogramdirectory.setText(_translate("reco_mainwin", "...", None))
        self.toolButton_4.setText(_translate("reco_mainwin", "...", None))
        self.testbutton.setText(_translate("reco_mainwin", "Test", None))
        self.submit.setText(_translate("reco_mainwin", "Submit", None))
        self.groupBox_5.setTitle(_translate("reco_mainwin", "Paganin", None))
        self.label_25.setText(_translate("reco_mainwin", "Pixel size [m]", None))
        self.label_24.setText(_translate("reco_mainwin", "Energy", None))
        self.label_27.setText(_translate("reco_mainwin", "Beta", None))
        self.label_28.setText(_translate("reco_mainwin", "Prop. distance [m]", None))
        self.label_26.setText(_translate("reco_mainwin", "Delta", None))
        self.groupBox_4.setTitle(_translate("reco_mainwin", "Reconstruction", None))
        self.geometry.setToolTip(_translate("reco_mainwin", "If \'none\', then the flag is not set at all.", None))
        self.geometry.setItemText(0, _translate("reco_mainwin", "none", None))
        self.geometry.setItemText(1, _translate("reco_mainwin", "sampling from 0->pi", None))
        self.geometry.setItemText(2, _translate("reco_mainwin", "angles in angle.txt", None))
        self.geometry.setItemText(3, _translate("reco_mainwin", "sampling from 0->2pi", None))
        self.label_40.setText(_translate("reco_mainwin", "Threshold (-H)", None))
        self.label_38.setText(_translate("reco_mainwin", "Edge-padding (-Z)", None))
        self.label_23.setText(_translate("reco_mainwin", "Output format (-t)", None))
        self.filter.setToolTip(_translate("reco_mainwin", "If \'none\', then the flag is not set at all.", None))
        self.filter.setItemText(0, _translate("reco_mainwin", "schepp", None))
        self.filter.setItemText(1, _translate("reco_mainwin", "hanning", None))
        self.filter.setItemText(2, _translate("reco_mainwin", "hamming", None))
        self.filter.setItemText(3, _translate("reco_mainwin", "ramlak", None))
        self.filter.setItemText(4, _translate("reco_mainwin", "parzen", None))
        self.filter.setItemText(5, _translate("reco_mainwin", "lanczos", None))
        self.filter.setItemText(6, _translate("reco_mainwin", "dpc", None))
        self.filter.setItemText(7, _translate("reco_mainwin", "none", None))
        self.label_17.setText(_translate("reco_mainwin", "Filter (-F)", None))
        self.label_37.setText(_translate("reco_mainwin", "Cutoff frequency (-U) ", None))
        self.outputtype.setToolTip(_translate("reco_mainwin", "If \'none\', then the flag is not set at all.", None))
        self.outputtype.setItemText(0, _translate("reco_mainwin", "TIF-8bit", None))
        self.outputtype.setItemText(1, _translate("reco_mainwin", "DMP", None))
        self.outputtype.setItemText(2, _translate("reco_mainwin", "DMP+HDF5", None))
        self.outputtype.setItemText(3, _translate("reco_mainwin", "TIF-16bit", None))
        self.outputtype.setItemText(4, _translate("reco_mainwin", "none", None))
        self.label_32.setText(_translate("reco_mainwin", "Geometry settings (-G)", None))
        self.label_39.setText(_translate("reco_mainwin", "Center of rotation (-c)", None))
        self.zingeron.setText(_translate("reco_mainwin", "Zinger removal", None))
        self.shiftcorrection.setText(_translate("reco_mainwin", "Correct for shift (-q)", None))
        self.label_31.setText(_translate("reco_mainwin", "Rotation angle (-a)", None))
        self.label_41.setText(_translate("reco_mainwin", "Width of smoothin kernel (-w)", None))
        self.groupBox_2.setTitle(_translate("reco_mainwin", "Ring Removal", None))
        self.wavelettype.setItemText(0, _translate("reco_mainwin", "db1", None))
        self.wavelettype.setItemText(1, _translate("reco_mainwin", "db2", None))
        self.wavelettype.setItemText(2, _translate("reco_mainwin", "db3", None))
        self.wavelettype.setItemText(3, _translate("reco_mainwin", "db4", None))
        self.wavelettype.setItemText(4, _translate("reco_mainwin", "db5", None))
        self.wavelettype.setItemText(5, _translate("reco_mainwin", "db6", None))
        self.wavelettype.setItemText(6, _translate("reco_mainwin", "db7", None))
        self.wavelettype.setItemText(7, _translate("reco_mainwin", "db8", None))
        self.wavelettype.setItemText(8, _translate("reco_mainwin", "db9", None))
        self.wavelettype.setItemText(9, _translate("reco_mainwin", "db10", None))
        self.wavelettype.setItemText(10, _translate("reco_mainwin", "db11", None))
        self.wavelettype.setItemText(11, _translate("reco_mainwin", "db12", None))
        self.wavelettype.setItemText(12, _translate("reco_mainwin", "db13", None))
        self.wavelettype.setItemText(13, _translate("reco_mainwin", "db14", None))
        self.wavelettype.setItemText(14, _translate("reco_mainwin", "db15", None))
        self.wavelettype.setItemText(15, _translate("reco_mainwin", "db16", None))
        self.wavelettype.setItemText(16, _translate("reco_mainwin", "db17", None))
        self.wavelettype.setItemText(17, _translate("reco_mainwin", "db18", None))
        self.wavelettype.setItemText(18, _translate("reco_mainwin", "db19", None))
        self.wavelettype.setItemText(19, _translate("reco_mainwin", "db20", None))
        self.label_5.setText(_translate("reco_mainwin", "Wavelettype (-y)", None))
        self.label_6.setText(_translate("reco_mainwin", "Decomposition level (-V)", None))
        self.label_7.setText(_translate("reco_mainwin", "Sigma in Gauss-filter (-E)", None))
        self.waveletpaddingmode.setItemText(0, _translate("reco_mainwin", "zero", None))
        self.waveletpaddingmode.setItemText(1, _translate("reco_mainwin", "constant", None))
        self.waveletpaddingmode.setItemText(2, _translate("reco_mainwin", "symmetric", None))
        self.waveletpaddingmode.setItemText(3, _translate("reco_mainwin", "periodic", None))
        self.waveletpaddingmode.setItemText(4, _translate("reco_mainwin", "smooth", None))
        self.label_8.setText(_translate("reco_mainwin", "Wavelet padding mode (-M)", None))
        self.label_9.setText(_translate("reco_mainwin", "Activate wavelet ring removal", None))
        self.clearfields.setText(_translate("reco_mainwin", "Clear", None))
        self.singleslice.setText(_translate("reco_mainwin", "Single slice", None))
        self.paganinon.setText(_translate("reco_mainwin", "Use Paganin phase retrieval (-Y)", None))
        self.cpron.setText(_translate("reco_mainwin", "Correct projections (create CPR)", None))
        self.reconstructon.setText(_translate("reco_mainwin", "Do reconstruction (-R)", None))
        self.sinon.setText(_translate("reco_mainwin", "Create sinograms (sin)", None))
        self.label_36.setText(_translate("reco_mainwin", "Interleave sino creation (-j)", None))
        self.menuMenu.setTitle(_translate("reco_mainwin", "Menu", None))
        self.menuScenarios.setTitle(_translate("reco_mainwin", "Scenarios", None))
        self.menuloadsettings.setText(_translate("reco_mainwin", "Load Settings", None))
        self.menusavesettings.setText(_translate("reco_mainwin", "Save settings", None))
        self.exitapp.setText(_translate("reco_mainwin", "Exit", None))
        self.actionCreate_only_CPR.setText(_translate("reco_mainwin", "Create only CPR", None))
        self.actionCreate_CPR_FLTP.setText(_translate("reco_mainwin", "Create CPR+FLTP", None))
        self.actionCreate_CPR_FLTP_sinograms.setText(_translate("reco_mainwin", "Create CPR+FLTP+sinograms", None))
        self.actionDo_everything_CPR_FLTP_Reconstruction.setText(_translate("reco_mainwin", "CPR+FLTP+Reconstruction", None))

