# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/main.ui'
#
# Created: Thu Jul 24 14:33:13 2014
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_reco_mainwin(object):
    def setupUi(self, reco_mainwin):
        reco_mainwin.setObjectName("reco_mainwin")
        reco_mainwin.resize(1251, 945)
        self.centralwidget = QtGui.QWidget(reco_mainwin)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 30, 301, 481))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 180, 281, 112))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.flats = QtGui.QLineEdit(self.gridLayoutWidget)
        self.flats.setObjectName("flats")
        self.gridLayout.addWidget(self.flats, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 2, 1, 1)
        self.interflats = QtGui.QLineEdit(self.gridLayoutWidget)
        self.interflats.setObjectName("interflats")
        self.gridLayout.addWidget(self.interflats, 2, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.raws = QtGui.QLineEdit(self.gridLayoutWidget)
        self.raws.setObjectName("raws")
        self.gridLayout.addWidget(self.raws, 1, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 2, 1, 1)
        self.darks = QtGui.QLineEdit(self.gridLayoutWidget)
        self.darks.setObjectName("darks")
        self.gridLayout.addWidget(self.darks, 1, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 0, 1, 2)
        self.flatfreq = QtGui.QLineEdit(self.gridLayoutWidget)
        self.flatfreq.setObjectName("flatfreq")
        self.gridLayout.addWidget(self.flatfreq, 3, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 4)
        self.line_5 = QtGui.QFrame(self.groupBox_3)
        self.line_5.setGeometry(QtCore.QRect(10, 280, 281, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 290, 283, 197))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 3, 2, 1, 1)
        self.binsize = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.binsize.setMinimumSize(QtCore.QSize(0, 27))
        self.binsize.setObjectName("binsize")
        self.gridLayout_3.addWidget(self.binsize, 6, 3, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 4, 2, 1, 1)
        self.roi_right = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.roi_right.setMinimumSize(QtCore.QSize(0, 27))
        self.roi_right.setObjectName("roi_right")
        self.gridLayout_3.addWidget(self.roi_right, 3, 3, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 4, 0, 1, 1)
        self.roi_lower = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.roi_lower.setMinimumSize(QtCore.QSize(0, 27))
        self.roi_lower.setObjectName("roi_lower")
        self.gridLayout_3.addWidget(self.roi_lower, 4, 3, 1, 1)
        self.label_33 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 6, 0, 1, 3)
        self.roi_upper = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.roi_upper.setMinimumSize(QtCore.QSize(0, 27))
        self.roi_upper.setObjectName("roi_upper")
        self.gridLayout_3.addWidget(self.roi_upper, 4, 1, 1, 1)
        self.line_19 = QtGui.QFrame(self.gridLayoutWidget_3)
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout_3.addWidget(self.line_19, 7, 0, 1, 4)
        self.roion = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.roion.setObjectName("roion")
        self.gridLayout_3.addWidget(self.roion, 2, 0, 1, 4)
        self.roi_left = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.roi_left.setMinimumSize(QtCore.QSize(0, 27))
        self.roi_left.setObjectName("roi_left")
        self.gridLayout_3.addWidget(self.roi_left, 3, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 3, 0, 1, 1)
        self.line_12 = QtGui.QFrame(self.gridLayoutWidget_3)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_3.addWidget(self.line_12, 1, 0, 1, 4)
        self.preflatsonly = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.preflatsonly.setObjectName("preflatsonly")
        self.gridLayout_3.addWidget(self.preflatsonly, 0, 0, 1, 4)
        self.line_18 = QtGui.QFrame(self.gridLayoutWidget_3)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_3.addWidget(self.line_18, 5, 0, 1, 4)
        self.label_34 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 8, 0, 1, 3)
        self.scaleimagefactor = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.scaleimagefactor.setMinimumSize(QtCore.QSize(0, 27))
        self.scaleimagefactor.setObjectName("scaleimagefactor")
        self.gridLayout_3.addWidget(self.scaleimagefactor, 8, 3, 1, 1)
        self.gridLayoutWidget_9 = QtGui.QWidget(self.groupBox_3)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(10, 27, 281, 151))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_8 = QtGui.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.prefix = QtGui.QLineEdit(self.gridLayoutWidget_9)
        self.prefix.setObjectName("prefix")
        self.gridLayout_8.addWidget(self.prefix, 3, 1, 1, 2)
        self.label = QtGui.QLabel(self.gridLayoutWidget_9)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 3, 0, 1, 1)
        self.label_44 = QtGui.QLabel(self.gridLayoutWidget_9)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 4, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.gridLayoutWidget_9)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_8.addWidget(self.line_4, 5, 0, 1, 3)
        self.stitchingtype = QtGui.QComboBox(self.gridLayoutWidget_9)
        self.stitchingtype.setObjectName("stitchingtype")
        self.stitchingtype.addItem("")
        self.stitchingtype.addItem("")
        self.stitchingtype.addItem("")
        self.gridLayout_8.addWidget(self.stitchingtype, 4, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_9)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 2, 0, 1, 1)
        self.inputtype = QtGui.QComboBox(self.gridLayoutWidget_9)
        self.inputtype.setObjectName("inputtype")
        self.inputtype.addItem("")
        self.inputtype.addItem("")
        self.inputtype.addItem("")
        self.inputtype.addItem("")
        self.gridLayout_8.addWidget(self.inputtype, 2, 1, 1, 2)
        self.inputdirectory = QtGui.QLineEdit(self.gridLayoutWidget_9)
        self.inputdirectory.setObjectName("inputdirectory")
        self.gridLayout_8.addWidget(self.inputdirectory, 1, 0, 1, 2)
        self.setinputdirectory = QtGui.QToolButton(self.gridLayoutWidget_9)
        self.setinputdirectory.setObjectName("setinputdirectory")
        self.gridLayout_8.addWidget(self.setinputdirectory, 1, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_9)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 0, 0, 1, 2)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(320, 220, 611, 611))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ImgViewer = QtGui.QLabel(self.frame)
        self.ImgViewer.setGeometry(QtCore.QRect(0, 0, 611, 611))
        self.ImgViewer.setObjectName("ImgViewer")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(410, 0, 441, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_18.setMinimumSize(QtCore.QSize(0, 21))
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 0, 1, 1)
        self.afsaccount = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.afsaccount.setMinimumSize(QtCore.QSize(0, 21))
        self.afsaccount.setObjectName("afsaccount")
        self.gridLayout_2.addWidget(self.afsaccount, 0, 1, 1, 1)
        self.cons2 = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.cons2.setMinimumSize(QtCore.QSize(0, 21))
        self.cons2.setObjectName("cons2")
        self.gridLayout_2.addWidget(self.cons2, 0, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 520, 301, 271))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_6 = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 30, 281, 231))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.setfltpdirectory = QtGui.QToolButton(self.gridLayoutWidget_6)
        self.setfltpdirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.setfltpdirectory.setObjectName("setfltpdirectory")
        self.gridLayout_6.addWidget(self.setfltpdirectory, 3, 1, 1, 1)
        self.sinograms = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.sinograms.setMinimumSize(QtCore.QSize(0, 26))
        self.sinograms.setObjectName("sinograms")
        self.gridLayout_6.addWidget(self.sinograms, 6, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.setcprdirectory = QtGui.QToolButton(self.gridLayoutWidget_6)
        self.setcprdirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.setcprdirectory.setObjectName("setcprdirectory")
        self.gridLayout_6.addWidget(self.setcprdirectory, 1, 1, 1, 1)
        self.sindirectory = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.sindirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.sindirectory.setObjectName("sindirectory")
        self.gridLayout_6.addWidget(self.sindirectory, 5, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 2, 0, 1, 1)
        self.cprdirectory = QtGui.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cprdirectory.sizePolicy().hasHeightForWidth())
        self.cprdirectory.setSizePolicy(sizePolicy)
        self.cprdirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.cprdirectory.setObjectName("cprdirectory")
        self.gridLayout_6.addWidget(self.cprdirectory, 1, 0, 1, 1)
        self.label_43 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_43.setObjectName("label_43")
        self.gridLayout_6.addWidget(self.label_43, 8, 0, 1, 1)
        self.setsinogramdirectory = QtGui.QToolButton(self.gridLayoutWidget_6)
        self.setsinogramdirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.setsinogramdirectory.setObjectName("setsinogramdirectory")
        self.gridLayout_6.addWidget(self.setsinogramdirectory, 5, 1, 1, 1)
        self.fltpdirectory = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.fltpdirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.fltpdirectory.setObjectName("fltpdirectory")
        self.gridLayout_6.addWidget(self.fltpdirectory, 3, 0, 1, 1)
        self.recodirectory = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.recodirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.recodirectory.setObjectName("recodirectory")
        self.gridLayout_6.addWidget(self.recodirectory, 9, 0, 1, 1)
        self.setrecodirectory = QtGui.QToolButton(self.gridLayoutWidget_6)
        self.setrecodirectory.setMinimumSize(QtCore.QSize(0, 22))
        self.setrecodirectory.setObjectName("setrecodirectory")
        self.gridLayout_6.addWidget(self.setrecodirectory, 9, 1, 1, 1)
        self.sinoslider = QtGui.QSlider(self.gridLayoutWidget_6)
        self.sinoslider.setOrientation(QtCore.Qt.Horizontal)
        self.sinoslider.setObjectName("sinoslider")
        self.gridLayout_6.addWidget(self.sinoslider, 7, 0, 1, 1)
        self.gridLayout_6.setRowMinimumHeight(6, 30)
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(320, 30, 301, 171))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget_4 = QtGui.QWidget(self.groupBox_5)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 281, 131))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_25 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 0, 3, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 0, 0, 1, 1)
        self.pag_delta = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.pag_delta.setObjectName("pag_delta")
        self.gridLayout_4.addWidget(self.pag_delta, 1, 1, 1, 2)
        self.pag_energy = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.pag_energy.setObjectName("pag_energy")
        self.gridLayout_4.addWidget(self.pag_energy, 0, 1, 1, 2)
        self.pag_pxsize = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.pag_pxsize.setObjectName("pag_pxsize")
        self.gridLayout_4.addWidget(self.pag_pxsize, 0, 4, 1, 1)
        self.label_27 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 1, 3, 1, 1)
        self.pag_beta = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.pag_beta.setObjectName("pag_beta")
        self.gridLayout_4.addWidget(self.pag_beta, 1, 4, 1, 1)
        self.label_28 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 2, 0, 1, 3)
        self.pag_distance = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.pag_distance.setObjectName("pag_distance")
        self.gridLayout_4.addWidget(self.pag_distance, 2, 3, 1, 2)
        self.label_26 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(940, 30, 301, 521))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_7 = QtGui.QWidget(self.groupBox_4)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 30, 281, 482))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.geometry = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.geometry.setObjectName("geometry")
        self.geometry.addItem("")
        self.geometry.addItem("")
        self.geometry.addItem("")
        self.geometry.addItem("")
        self.gridLayout_7.addWidget(self.geometry, 18, 0, 1, 2)
        self.label_40 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 21, 0, 1, 1)
        self.edgepadding = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.edgepadding.setObjectName("edgepadding")
        self.gridLayout_7.addWidget(self.edgepadding, 5, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 5, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 9, 0, 1, 1)
        self.filter = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.filter.setObjectName("filter")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.gridLayout_7.addWidget(self.filter, 0, 1, 1, 1)
        self.line_16 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_7.addWidget(self.line_16, 16, 0, 1, 2)
        self.line_13 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_7.addWidget(self.line_13, 12, 0, 1, 2)
        self.rotationangle = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.rotationangle.setObjectName("rotationangle")
        self.gridLayout_7.addWidget(self.rotationangle, 15, 1, 1, 1)
        self.line_7 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_7.addWidget(self.line_7, 1, 0, 1, 2)
        self.centerofrotation = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.centerofrotation.setObjectName("centerofrotation")
        self.gridLayout_7.addWidget(self.centerofrotation, 7, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 3, 0, 1, 1)
        self.outputtype = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.outputtype.setObjectName("outputtype")
        self.outputtype.addItem("")
        self.outputtype.addItem("")
        self.outputtype.addItem("")
        self.outputtype.addItem("")
        self.outputtype.addItem("")
        self.gridLayout_7.addWidget(self.outputtype, 9, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_32.setObjectName("label_32")
        self.gridLayout_7.addWidget(self.label_32, 17, 0, 1, 1)
        self.label_39 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 7, 0, 1, 1)
        self.line_10 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_7.addWidget(self.line_10, 8, 0, 1, 2)
        self.zingeron = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.zingeron.setObjectName("zingeron")
        self.gridLayout_7.addWidget(self.zingeron, 20, 0, 1, 1)
        self.cutofffrequency = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.cutofffrequency.setObjectName("cutofffrequency")
        self.gridLayout_7.addWidget(self.cutofffrequency, 3, 1, 1, 1)
        self.shiftcorrection = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.shiftcorrection.setObjectName("shiftcorrection")
        self.gridLayout_7.addWidget(self.shiftcorrection, 13, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 15, 0, 1, 1)
        self.line_14 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_7.addWidget(self.line_14, 14, 0, 1, 2)
        self.line_9 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_7.addWidget(self.line_9, 4, 0, 1, 2)
        self.line_21 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout_7.addWidget(self.line_21, 19, 0, 1, 2)
        self.line_11 = QtGui.QFrame(self.gridLayoutWidget_7)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_7.addWidget(self.line_11, 6, 0, 1, 2)
        self.label_41 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_41.setMinimumSize(QtCore.QSize(0, 35))
        self.label_41.setWordWrap(True)
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 22, 0, 1, 1)
        self.zinger_thresh = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.zinger_thresh.setObjectName("zinger_thresh")
        self.gridLayout_7.addWidget(self.zinger_thresh, 21, 1, 1, 1)
        self.zinger_width = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.zinger_width.setObjectName("zinger_width")
        self.gridLayout_7.addWidget(self.zinger_width, 22, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 10, 0, 1, 1)
        self.tifmin = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.tifmin.setObjectName("tifmin")
        self.gridLayout_7.addWidget(self.tifmin, 10, 1, 1, 1)
        self.label_42 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.label_42.setObjectName("label_42")
        self.gridLayout_7.addWidget(self.label_42, 11, 0, 1, 1)
        self.tifmax = QtGui.QLineEdit(self.gridLayoutWidget_7)
        self.tifmax.setObjectName("tifmax")
        self.gridLayout_7.addWidget(self.tifmax, 11, 1, 1, 1)
        self.zingermode = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.zingermode.setObjectName("zingermode")
        self.zingermode.addItem("")
        self.zingermode.addItem("")
        self.gridLayout_7.addWidget(self.zingermode, 20, 1, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(940, 550, 301, 301))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayoutWidget_5 = QtGui.QWidget(self.groupBox_6)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 293, 271))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.paganinon = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.paganinon.setObjectName("paganinon")
        self.gridLayout_5.addWidget(self.paganinon, 2, 0, 1, 3)
        self.cpron = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.cpron.setObjectName("cpron")
        self.gridLayout_5.addWidget(self.cpron, 0, 0, 1, 3)
        self.reconstructon = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.reconstructon.setObjectName("reconstructon")
        self.gridLayout_5.addWidget(self.reconstructon, 7, 0, 1, 3)
        self.sinon = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.sinon.setObjectName("sinon")
        self.gridLayout_5.addWidget(self.sinon, 4, 0, 1, 3)
        self.steplines = QtGui.QLineEdit(self.gridLayoutWidget_5)
        self.steplines.setMinimumSize(QtCore.QSize(0, 27))
        self.steplines.setMaximumSize(QtCore.QSize(50, 16777215))
        self.steplines.setObjectName("steplines")
        self.gridLayout_5.addWidget(self.steplines, 6, 3, 1, 1)
        self.label_36 = QtGui.QLabel(self.gridLayoutWidget_5)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 6, 0, 1, 3)
        self.withlog = QtGui.QCheckBox(self.gridLayoutWidget_5)
        self.withlog.setObjectName("withlog")
        self.gridLayout_5.addWidget(self.withlog, 1, 1, 1, 2)
        self.widget = QtGui.QWidget(self.gridLayoutWidget_5)
        self.widget.setMinimumSize(QtCore.QSize(0, 30))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtGui.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 191, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fltp_fromtif = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.fltp_fromtif.setObjectName("fltp_fromtif")
        self.horizontalLayout.addWidget(self.fltp_fromtif)
        self.fltp_fromcpr = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.fltp_fromcpr.setObjectName("fltp_fromcpr")
        self.horizontalLayout.addWidget(self.fltp_fromcpr)
        self.gridLayout_5.addWidget(self.widget, 3, 1, 1, 3)
        self.widget_2 = QtGui.QWidget(self.gridLayoutWidget_5)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_2.setObjectName("widget_2")
        self.layoutWidget = QtGui.QWidget(self.widget_2)
        self.layoutWidget.setGeometry(QtCore.QRect(5, 2, 211, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rec_fromtif = QtGui.QRadioButton(self.layoutWidget)
        self.rec_fromtif.setMinimumSize(QtCore.QSize(0, 21))
        self.rec_fromtif.setObjectName("rec_fromtif")
        self.horizontalLayout_3.addWidget(self.rec_fromtif)
        self.rec_fromsino = QtGui.QRadioButton(self.layoutWidget)
        self.rec_fromsino.setMinimumSize(QtCore.QSize(0, 21))
        self.rec_fromsino.setObjectName("rec_fromsino")
        self.horizontalLayout_3.addWidget(self.rec_fromsino)
        self.gridLayout_5.addWidget(self.widget_2, 8, 0, 1, 3)
        self.widget_3 = QtGui.QWidget(self.gridLayoutWidget_5)
        self.widget_3.setEnabled(True)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_3.setObjectName("widget_3")
        self.layoutWidget1 = QtGui.QWidget(self.widget_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 280, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sin_fromtif = QtGui.QRadioButton(self.layoutWidget1)
        self.sin_fromtif.setMinimumSize(QtCore.QSize(90, 0))
        self.sin_fromtif.setObjectName("sin_fromtif")
        self.horizontalLayout_4.addWidget(self.sin_fromtif)
        self.sin_fromcpr = QtGui.QRadioButton(self.layoutWidget1)
        self.sin_fromcpr.setMinimumSize(QtCore.QSize(90, 0))
        self.sin_fromcpr.setObjectName("sin_fromcpr")
        self.horizontalLayout_4.addWidget(self.sin_fromcpr)
        self.sin_fromfltp = QtGui.QRadioButton(self.layoutWidget1)
        self.sin_fromfltp.setMinimumSize(QtCore.QSize(90, 0))
        self.sin_fromfltp.setObjectName("sin_fromfltp")
        self.horizontalLayout_4.addWidget(self.sin_fromfltp)
        self.gridLayout_5.addWidget(self.widget_3, 5, 0, 1, 4)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 820, 231, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_30 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_2.addWidget(self.label_30)
        self.jobname = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.jobname.setMinimumSize(QtCore.QSize(0, 27))
        self.jobname.setObjectName("jobname")
        self.horizontalLayout_2.addWidget(self.jobname)
        self.gridLayoutWidget_8 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(10, 860, 1061, 32))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_9 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.singleslice = QtGui.QPushButton(self.gridLayoutWidget_8)
        self.singleslice.setMinimumSize(QtCore.QSize(175, 0))
        self.singleslice.setObjectName("singleslice")
        self.gridLayout_9.addWidget(self.singleslice, 0, 3, 1, 1)
        self.submit = QtGui.QPushButton(self.gridLayoutWidget_8)
        self.submit.setMinimumSize(QtCore.QSize(175, 0))
        self.submit.setObjectName("submit")
        self.gridLayout_9.addWidget(self.submit, 0, 0, 1, 1)
        self.clearfields = QtGui.QPushButton(self.gridLayoutWidget_8)
        self.clearfields.setObjectName("clearfields")
        self.gridLayout_9.addWidget(self.clearfields, 0, 2, 1, 1)
        self.print_cmd = QtGui.QCheckBox(self.gridLayoutWidget_8)
        self.print_cmd.setObjectName("print_cmd")
        self.gridLayout_9.addWidget(self.print_cmd, 0, 4, 1, 1)
        self.develbranchon = QtGui.QCheckBox(self.gridLayoutWidget_8)
        self.develbranchon.setObjectName("develbranchon")
        self.gridLayout_9.addWidget(self.develbranchon, 0, 5, 1, 1)
        self.jobpriority = QtGui.QComboBox(self.gridLayoutWidget_8)
        self.jobpriority.setObjectName("jobpriority")
        self.jobpriority.addItem("")
        self.jobpriority.addItem("")
        self.jobpriority.addItem("")
        self.gridLayout_9.addWidget(self.jobpriority, 0, 1, 1, 1)
        self.openinfiji = QtGui.QCheckBox(self.centralwidget)
        self.openinfiji.setGeometry(QtCore.QRect(320, 830, 291, 23))
        self.openinfiji.setObjectName("openinfiji")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(630, 30, 301, 181))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_10 = QtGui.QWidget(self.tab)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(0, 0, 291, 151))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_11 = QtGui.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.wavelettype = QtGui.QComboBox(self.gridLayoutWidget_10)
        self.wavelettype.setObjectName("wavelettype")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.wavelettype.addItem("")
        self.gridLayout_11.addWidget(self.wavelettype, 1, 2, 1, 1)
        self.waveletpaddingmode = QtGui.QComboBox(self.gridLayoutWidget_10)
        self.waveletpaddingmode.setObjectName("waveletpaddingmode")
        self.waveletpaddingmode.addItem("")
        self.waveletpaddingmode.addItem("")
        self.waveletpaddingmode.addItem("")
        self.waveletpaddingmode.addItem("")
        self.waveletpaddingmode.addItem("")
        self.gridLayout_11.addWidget(self.waveletpaddingmode, 2, 2, 1, 1)
        self.waveletdecompositionlevel = QtGui.QLineEdit(self.gridLayoutWidget_10)
        self.waveletdecompositionlevel.setObjectName("waveletdecompositionlevel")
        self.gridLayout_11.addWidget(self.waveletdecompositionlevel, 3, 2, 1, 1)
        self.sigmaingaussfilter = QtGui.QLineEdit(self.gridLayoutWidget_10)
        self.sigmaingaussfilter.setObjectName("sigmaingaussfilter")
        self.gridLayout_11.addWidget(self.sigmaingaussfilter, 4, 2, 1, 1)
        self.runringremoval = QtGui.QCheckBox(self.gridLayoutWidget_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runringremoval.sizePolicy().hasHeightForWidth())
        self.runringremoval.setSizePolicy(sizePolicy)
        self.runringremoval.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.runringremoval.setObjectName("runringremoval")
        self.gridLayout_11.addWidget(self.runringremoval, 0, 0, 1, 3)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 1, 0, 1, 2)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_8.setObjectName("label_8")
        self.gridLayout_11.addWidget(self.label_8, 2, 0, 1, 2)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 3, 0, 1, 2)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_10)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 4, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_11 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(6, 9, 281, 121))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_10 = QtGui.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.runringremovalstd = QtGui.QCheckBox(self.gridLayoutWidget_11)
        self.runringremovalstd.setObjectName("runringremovalstd")
        self.gridLayout_10.addWidget(self.runringremovalstd, 0, 0, 1, 2)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_11)
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 1, 0, 1, 1)
        self.ring_std_mode = QtGui.QComboBox(self.gridLayoutWidget_11)
        self.ring_std_mode.setObjectName("ring_std_mode")
        self.ring_std_mode.addItem("")
        self.ring_std_mode.addItem("")
        self.ring_std_mode.addItem("")
        self.gridLayout_10.addWidget(self.ring_std_mode, 1, 1, 1, 1)
        self.label_45 = QtGui.QLabel(self.gridLayoutWidget_11)
        self.label_45.setObjectName("label_45")
        self.gridLayout_10.addWidget(self.label_45, 2, 0, 1, 1)
        self.ring_std_diff = QtGui.QLineEdit(self.gridLayoutWidget_11)
        self.ring_std_diff.setObjectName("ring_std_diff")
        self.gridLayout_10.addWidget(self.ring_std_diff, 2, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.gridLayoutWidget_11)
        self.label_46.setObjectName("label_46")
        self.gridLayout_10.addWidget(self.label_46, 3, 0, 1, 1)
        self.ring_std_ringwidth = QtGui.QLineEdit(self.gridLayoutWidget_11)
        self.ring_std_ringwidth.setObjectName("ring_std_ringwidth")
        self.gridLayout_10.addWidget(self.ring_std_ringwidth, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        reco_mainwin.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(reco_mainwin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1251, 23))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuLoad_specific = QtGui.QMenu(self.menuMenu)
        self.menuLoad_specific.setObjectName("menuLoad_specific")
        self.menuRun = QtGui.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuReconstruction = QtGui.QMenu(self.menuRun)
        self.menuReconstruction.setObjectName("menuReconstruction")
        self.menuProjections = QtGui.QMenu(self.menuRun)
        self.menuProjections.setObjectName("menuProjections")
        self.menuSinograms = QtGui.QMenu(self.menuRun)
        self.menuSinograms.setObjectName("menuSinograms")
        self.menuRing_removal = QtGui.QMenu(self.menuRun)
        self.menuRing_removal.setObjectName("menuRing_removal")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuChange_Target = QtGui.QMenu(self.menuSettings)
        self.menuChange_Target.setObjectName("menuChange_Target")
        reco_mainwin.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(reco_mainwin)
        self.statusbar.setObjectName("statusbar")
        reco_mainwin.setStatusBar(self.statusbar)
        self.menuloadsettings = QtGui.QAction(reco_mainwin)
        self.menuloadsettings.setObjectName("menuloadsettings")
        self.menusavesettings = QtGui.QAction(reco_mainwin)
        self.menusavesettings.setObjectName("menusavesettings")
        self.exitapp = QtGui.QAction(reco_mainwin)
        self.exitapp.setObjectName("exitapp")
        self.menuCreateRecoStandard = QtGui.QAction(reco_mainwin)
        self.menuCreateRecoStandard.setObjectName("menuCreateRecoStandard")
        self.menuCreateRecoPaganin = QtGui.QAction(reco_mainwin)
        self.menuCreateRecoPaganin.setObjectName("menuCreateRecoPaganin")
        self.menuCreateCpr = QtGui.QAction(reco_mainwin)
        self.menuCreateCpr.setObjectName("menuCreateCpr")
        self.menuCreateCprLog = QtGui.QAction(reco_mainwin)
        self.menuCreateCprLog.setObjectName("menuCreateCprLog")
        self.menuCreateFltp = QtGui.QAction(reco_mainwin)
        self.menuCreateFltp.setObjectName("menuCreateFltp")
        self.menuCreateFltpCpr = QtGui.QAction(reco_mainwin)
        self.menuCreateFltpCpr.setObjectName("menuCreateFltpCpr")
        self.menuCreateSinosQuick = QtGui.QAction(reco_mainwin)
        self.menuCreateSinosQuick.setObjectName("menuCreateSinosQuick")
        self.menuCreateSinosFromTif = QtGui.QAction(reco_mainwin)
        self.menuCreateSinosFromTif.setObjectName("menuCreateSinosFromTif")
        self.menuCreateSinosFromFltp = QtGui.QAction(reco_mainwin)
        self.menuCreateSinosFromFltp.setObjectName("menuCreateSinosFromFltp")
        self.menuRingRemoval1 = QtGui.QAction(reco_mainwin)
        self.menuRingRemoval1.setObjectName("menuRingRemoval1")
        self.menuRingRemoval2 = QtGui.QAction(reco_mainwin)
        self.menuRingRemoval2.setObjectName("menuRingRemoval2")
        self.menuLoadOnlyPaganin = QtGui.QAction(reco_mainwin)
        self.menuLoadOnlyPaganin.setObjectName("menuLoadOnlyPaganin")
        self.menuLoadOnlyRingRemoval = QtGui.QAction(reco_mainwin)
        self.menuLoadOnlyRingRemoval.setObjectName("menuLoadOnlyRingRemoval")
        self.menuChangeMerlinMountPoint = QtGui.QAction(reco_mainwin)
        self.menuChangeMerlinMountPoint.setObjectName("menuChangeMerlinMountPoint")
        self.menuChangeTargetoX02da = QtGui.QAction(reco_mainwin)
        self.menuChangeTargetoX02da.setObjectName("menuChangeTargetoX02da")
        self.menuChangeTargetoMerlin = QtGui.QAction(reco_mainwin)
        self.menuChangeTargetoMerlin.setObjectName("menuChangeTargetoMerlin")
        self.menuLoad_specific.addAction(self.menuLoadOnlyPaganin)
        self.menuLoad_specific.addAction(self.menuLoadOnlyRingRemoval)
        self.menuMenu.addAction(self.menuloadsettings)
        self.menuMenu.addAction(self.menusavesettings)
        self.menuMenu.addAction(self.menuLoad_specific.menuAction())
        self.menuMenu.addAction(self.exitapp)
        self.menuReconstruction.addAction(self.menuCreateRecoStandard)
        self.menuReconstruction.addAction(self.menuCreateRecoPaganin)
        self.menuProjections.addAction(self.menuCreateCpr)
        self.menuProjections.addAction(self.menuCreateCprLog)
        self.menuProjections.addAction(self.menuCreateFltp)
        self.menuProjections.addAction(self.menuCreateFltpCpr)
        self.menuSinograms.addAction(self.menuCreateSinosQuick)
        self.menuSinograms.addAction(self.menuCreateSinosFromTif)
        self.menuSinograms.addAction(self.menuCreateSinosFromFltp)
        self.menuRing_removal.addAction(self.menuRingRemoval1)
        self.menuRing_removal.addAction(self.menuRingRemoval2)
        self.menuRun.addAction(self.menuProjections.menuAction())
        self.menuRun.addAction(self.menuSinograms.menuAction())
        self.menuRun.addAction(self.menuReconstruction.menuAction())
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.menuRing_removal.menuAction())
        self.menuChange_Target.addAction(self.menuChangeTargetoX02da)
        self.menuChange_Target.addAction(self.menuChangeTargetoMerlin)
        self.menuSettings.addAction(self.menuChangeMerlinMountPoint)
        self.menuSettings.addAction(self.menuChange_Target.menuAction())
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(reco_mainwin)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(reco_mainwin)

    def retranslateUi(self, reco_mainwin):
        reco_mainwin.setWindowTitle(QtGui.QApplication.translate("reco_mainwin", "GRecoMan 1.1.4-5-gb91d32b 1.1.4", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("reco_mainwin", "Input Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("reco_mainwin", "Flats", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("reco_mainwin", "Interflats", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("reco_mainwin", "Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("reco_mainwin", "Darks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("reco_mainwin", "Flat frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("reco_mainwin", "Scan parameters (-f): Number of images", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("reco_mainwin", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("reco_mainwin", "Lower", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("reco_mainwin", "Upper", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("reco_mainwin", "Binning size (-b)", None, QtGui.QApplication.UnicodeUTF8))
        self.roion.setText(QtGui.QApplication.translate("reco_mainwin", "Region of interest in projection (-r)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("reco_mainwin", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.preflatsonly.setText(QtGui.QApplication.translate("reco_mainwin", "Use only preflats (-u)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("reco_mainwin", "Scale factor of raw img-s (-s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("reco_mainwin", "Prefix (-p)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("reco_mainwin", "Stiching/360 (-S)", None, QtGui.QApplication.UnicodeUTF8))
        self.stitchingtype.setItemText(0, QtGui.QApplication.translate("reco_mainwin", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.stitchingtype.setItemText(1, QtGui.QApplication.translate("reco_mainwin", "left", None, QtGui.QApplication.UnicodeUTF8))
        self.stitchingtype.setItemText(2, QtGui.QApplication.translate("reco_mainwin", "right", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("reco_mainwin", "Input type (-I)", None, QtGui.QApplication.UnicodeUTF8))
        self.inputtype.setItemText(0, QtGui.QApplication.translate("reco_mainwin", "DMP", None, QtGui.QApplication.UnicodeUTF8))
        self.inputtype.setItemText(1, QtGui.QApplication.translate("reco_mainwin", "HDF5", None, QtGui.QApplication.UnicodeUTF8))
        self.inputtype.setItemText(2, QtGui.QApplication.translate("reco_mainwin", "TIF", None, QtGui.QApplication.UnicodeUTF8))
        self.inputtype.setItemText(3, QtGui.QApplication.translate("reco_mainwin", "DMP sinos", None, QtGui.QApplication.UnicodeUTF8))
        self.setinputdirectory.setText(QtGui.QApplication.translate("reco_mainwin", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("reco_mainwin", "Input directory (TIF folder)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("reco_mainwin", "Application is running on:", None, QtGui.QApplication.UnicodeUTF8))
        self.afsaccount.setText(QtGui.QApplication.translate("reco_mainwin", "AFS-account", None, QtGui.QApplication.UnicodeUTF8))
        self.cons2.setText(QtGui.QApplication.translate("reco_mainwin", "x02da-cons-2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("reco_mainwin", "Input/Output directories", None, QtGui.QApplication.UnicodeUTF8))
        self.setfltpdirectory.setText(QtGui.QApplication.translate("reco_mainwin", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("reco_mainwin", "Corrected projections (CPR-s)", None, QtGui.QApplication.UnicodeUTF8))
        self.setcprdirectory.setText(QtGui.QApplication.translate("reco_mainwin", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("reco_mainwin", "Sinograms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("reco_mainwin", "Filtered projections (FLTP-s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("reco_mainwin", "Reconstructions", None, QtGui.QApplication.UnicodeUTF8))
        self.setsinogramdirectory.setText(QtGui.QApplication.translate("reco_mainwin", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.setrecodirectory.setText(QtGui.QApplication.translate("reco_mainwin", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("reco_mainwin", "Paganin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("reco_mainwin", "Pixel size [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("reco_mainwin", "Energy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("reco_mainwin", "Beta", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("reco_mainwin", "Prop. distance [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("reco_mainwin", "Delta", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("reco_mainwin", "Reconstruction", None, QtGui.QApplication.UnicodeUTF8))
        self.geometry.setToolTip(QtGui.QApplication.translate("reco_mainwin", "If \'none\', then the flag is not set at all.", None, QtGui.QApplication.UnicodeUTF8))
        self.geometry.setItemText(0, QtGui.QApplication.translate("reco_mainwin", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.geometry.setItemText(1, QtGui.QApplication.translate("reco_mainwin", "sampling from 0->pi", None, QtGui.QApplication.UnicodeUTF8))
        self.geometry.setItemText(2, QtGui.QApplication.translate("reco_mainwin", "angles in angles.txt", None, QtGui.QApplication.UnicodeUTF8))
        self.geometry.setItemText(3, QtGui.QApplication.translate("reco_mainwin", "sampling from 0->2pi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("reco_mainwin", "Threshold (-H)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("reco_mainwin", "Edge-padding (-Z)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("reco_mainwin", "Output format (-t)", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setToolTip(QtGui.QApplication.translate("reco_mainwin", "If \'none\', then the flag is not set at all.", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setItemText(0, QtGui.QApplication.translate("reco_mainwin", "schepp", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setItemText(1, QtGui.QApplication.translate("reco_mainwin", "hanning", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setItemText(2, QtGui.QApplication.translate("reco_mainwin", "hamming", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setItemText(3, QtGui.QApplication.translate("reco_mainwin", "ramlak", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setItemText(4, QtGui.QApplication.translate("reco_mainwin", "parzen", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setItemText(5, QtGui.QApplication.translate("reco_mainwin", "lanczos", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setItemText(6, QtGui.QApplication.translate("reco_mainwin", "dpc", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setItemText(7, QtGui.QApplication.translate("reco_mainwin", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("reco_mainwin", "Filter (-F)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("reco_mainwin", "Cutoff frequency (-U) ", None, QtGui.QApplication.UnicodeUTF8))
        self.outputtype.setToolTip(QtGui.QApplication.translate("reco_mainwin", "If \'none\', then the flag is not set at all.", None, QtGui.QApplication.UnicodeUTF8))
        self.outputtype.setItemText(0, QtGui.QApplication.translate("reco_mainwin", "TIF-8bit", None, QtGui.QApplication.UnicodeUTF8))
        self.outputtype.setItemText(1, QtGui.QApplication.translate("reco_mainwin", "DMP", None, QtGui.QApplication.UnicodeUTF8))
        self.outputtype.setItemText(2, QtGui.QApplication.translate("reco_mainwin", "DMP+HDF5", None, QtGui.QApplication.UnicodeUTF8))
        self.outputtype.setItemText(3, QtGui.QApplication.translate("reco_mainwin", "TIF-16bit", None, QtGui.QApplication.UnicodeUTF8))
        self.outputtype.setItemText(4, QtGui.QApplication.translate("reco_mainwin", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("reco_mainwin", "Geometry settings (-G)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("reco_mainwin", "Center of rotation (-c)", None, QtGui.QApplication.UnicodeUTF8))
        self.zingeron.setToolTip(QtGui.QApplication.translate("reco_mainwin", "If 1D is selected the zinger removal is applied during the reconstruction step on a sinogram. In de 2D version (not implemented yet) it is applied on a corrected projection, before creating the sinogram.", None, QtGui.QApplication.UnicodeUTF8))
        self.zingeron.setText(QtGui.QApplication.translate("reco_mainwin", "Zinger removal", None, QtGui.QApplication.UnicodeUTF8))
        self.shiftcorrection.setText(QtGui.QApplication.translate("reco_mainwin", "Correct for shift (-q)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("reco_mainwin", "Rotation angle (-a)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("reco_mainwin", "Width of smoothin kernel (-w)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("reco_mainwin", "Min. value for tif (-n)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("reco_mainwin", "Max. value for tif (-x)", None, QtGui.QApplication.UnicodeUTF8))
        self.zingermode.setItemText(0, QtGui.QApplication.translate("reco_mainwin", "1D", None, QtGui.QApplication.UnicodeUTF8))
        self.zingermode.setItemText(1, QtGui.QApplication.translate("reco_mainwin", "2D", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("reco_mainwin", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.paganinon.setText(QtGui.QApplication.translate("reco_mainwin", "Paganin phase retrieval (fltp)", None, QtGui.QApplication.UnicodeUTF8))
        self.cpron.setText(QtGui.QApplication.translate("reco_mainwin", "Create CPR-s", None, QtGui.QApplication.UnicodeUTF8))
        self.reconstructon.setText(QtGui.QApplication.translate("reco_mainwin", "Do reconstruction", None, QtGui.QApplication.UnicodeUTF8))
        self.sinon.setText(QtGui.QApplication.translate("reco_mainwin", "Create sinograms (sin)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("reco_mainwin", "Interleave sino creation (-j)", None, QtGui.QApplication.UnicodeUTF8))
        self.withlog.setText(QtGui.QApplication.translate("reco_mainwin", "with log correction", None, QtGui.QApplication.UnicodeUTF8))
        self.fltp_fromtif.setText(QtGui.QApplication.translate("reco_mainwin", "from TIF", None, QtGui.QApplication.UnicodeUTF8))
        self.fltp_fromcpr.setText(QtGui.QApplication.translate("reco_mainwin", "from cpr", None, QtGui.QApplication.UnicodeUTF8))
        self.rec_fromtif.setText(QtGui.QApplication.translate("reco_mainwin", "from TIF", None, QtGui.QApplication.UnicodeUTF8))
        self.rec_fromsino.setText(QtGui.QApplication.translate("reco_mainwin", "from sino", None, QtGui.QApplication.UnicodeUTF8))
        self.sin_fromtif.setText(QtGui.QApplication.translate("reco_mainwin", "from tif", None, QtGui.QApplication.UnicodeUTF8))
        self.sin_fromcpr.setText(QtGui.QApplication.translate("reco_mainwin", "from cpr", None, QtGui.QApplication.UnicodeUTF8))
        self.sin_fromfltp.setText(QtGui.QApplication.translate("reco_mainwin", "from fltp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("reco_mainwin", "Job name:", None, QtGui.QApplication.UnicodeUTF8))
        self.singleslice.setText(QtGui.QApplication.translate("reco_mainwin", "Single slice", None, QtGui.QApplication.UnicodeUTF8))
        self.submit.setText(QtGui.QApplication.translate("reco_mainwin", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.clearfields.setText(QtGui.QApplication.translate("reco_mainwin", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.print_cmd.setText(QtGui.QApplication.translate("reco_mainwin", "Print command line string (debug)", None, QtGui.QApplication.UnicodeUTF8))
        self.develbranchon.setText(QtGui.QApplication.translate("reco_mainwin", "Use SGE \"devel\" branch", None, QtGui.QApplication.UnicodeUTF8))
        self.jobpriority.setItemText(0, QtGui.QApplication.translate("reco_mainwin", "Normal priority", None, QtGui.QApplication.UnicodeUTF8))
        self.jobpriority.setItemText(1, QtGui.QApplication.translate("reco_mainwin", "Low priority", None, QtGui.QApplication.UnicodeUTF8))
        self.jobpriority.setItemText(2, QtGui.QApplication.translate("reco_mainwin", "Very low priority", None, QtGui.QApplication.UnicodeUTF8))
        self.openinfiji.setText(QtGui.QApplication.translate("reco_mainwin", "Open preview image in Fiji (externally)", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(0, QtGui.QApplication.translate("reco_mainwin", "db1", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(1, QtGui.QApplication.translate("reco_mainwin", "db2", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(2, QtGui.QApplication.translate("reco_mainwin", "db3", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(3, QtGui.QApplication.translate("reco_mainwin", "db4", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(4, QtGui.QApplication.translate("reco_mainwin", "db5", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(5, QtGui.QApplication.translate("reco_mainwin", "db6", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(6, QtGui.QApplication.translate("reco_mainwin", "db7", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(7, QtGui.QApplication.translate("reco_mainwin", "db8", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(8, QtGui.QApplication.translate("reco_mainwin", "db9", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(9, QtGui.QApplication.translate("reco_mainwin", "db10", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(10, QtGui.QApplication.translate("reco_mainwin", "db11", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(11, QtGui.QApplication.translate("reco_mainwin", "db12", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(12, QtGui.QApplication.translate("reco_mainwin", "db13", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(13, QtGui.QApplication.translate("reco_mainwin", "db14", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(14, QtGui.QApplication.translate("reco_mainwin", "db15", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(15, QtGui.QApplication.translate("reco_mainwin", "db16", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(16, QtGui.QApplication.translate("reco_mainwin", "db17", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(17, QtGui.QApplication.translate("reco_mainwin", "db18", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(18, QtGui.QApplication.translate("reco_mainwin", "db19", None, QtGui.QApplication.UnicodeUTF8))
        self.wavelettype.setItemText(19, QtGui.QApplication.translate("reco_mainwin", "db20", None, QtGui.QApplication.UnicodeUTF8))
        self.waveletpaddingmode.setItemText(0, QtGui.QApplication.translate("reco_mainwin", "zero", None, QtGui.QApplication.UnicodeUTF8))
        self.waveletpaddingmode.setItemText(1, QtGui.QApplication.translate("reco_mainwin", "constant", None, QtGui.QApplication.UnicodeUTF8))
        self.waveletpaddingmode.setItemText(2, QtGui.QApplication.translate("reco_mainwin", "symmetric", None, QtGui.QApplication.UnicodeUTF8))
        self.waveletpaddingmode.setItemText(3, QtGui.QApplication.translate("reco_mainwin", "periodic", None, QtGui.QApplication.UnicodeUTF8))
        self.waveletpaddingmode.setItemText(4, QtGui.QApplication.translate("reco_mainwin", "smooth", None, QtGui.QApplication.UnicodeUTF8))
        self.runringremoval.setText(QtGui.QApplication.translate("reco_mainwin", "Activate wavelet ring removal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("reco_mainwin", "Wavelettype (-y)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("reco_mainwin", "Padding mode (-M)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("reco_mainwin", "Decomposition level (-V)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("reco_mainwin", "Sigma in Gauss-filter (-E)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("reco_mainwin", "Ring Removal I", None, QtGui.QApplication.UnicodeUTF8))
        self.runringremovalstd.setText(QtGui.QApplication.translate("reco_mainwin", "Activate standard ring removal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("reco_mainwin", "Mode (-L)", None, QtGui.QApplication.UnicodeUTF8))
        self.ring_std_mode.setItemText(0, QtGui.QApplication.translate("reco_mainwin", "standard", None, QtGui.QApplication.UnicodeUTF8))
        self.ring_std_mode.setItemText(1, QtGui.QApplication.translate("reco_mainwin", "shift by 1", None, QtGui.QApplication.UnicodeUTF8))
        self.ring_std_mode.setItemText(2, QtGui.QApplication.translate("reco_mainwin", "MBA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setToolTip(QtGui.QApplication.translate("reco_mainwin", "Difference in standard deviation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("reco_mainwin", "Diff. in std.deviation (-D)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("reco_mainwin", "Max. ring width in px (-W)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("reco_mainwin", "Ring removal II", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("reco_mainwin", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLoad_specific.setTitle(QtGui.QApplication.translate("reco_mainwin", "Load specific", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRun.setTitle(QtGui.QApplication.translate("reco_mainwin", "Templates", None, QtGui.QApplication.UnicodeUTF8))
        self.menuReconstruction.setTitle(QtGui.QApplication.translate("reco_mainwin", "Reconstruction", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProjections.setTitle(QtGui.QApplication.translate("reco_mainwin", "Projections", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSinograms.setTitle(QtGui.QApplication.translate("reco_mainwin", "Sinograms", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRing_removal.setTitle(QtGui.QApplication.translate("reco_mainwin", "Ring removal", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("reco_mainwin", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuChange_Target.setTitle(QtGui.QApplication.translate("reco_mainwin", "Change Target to", None, QtGui.QApplication.UnicodeUTF8))
        self.menuloadsettings.setText(QtGui.QApplication.translate("reco_mainwin", "Load Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menusavesettings.setText(QtGui.QApplication.translate("reco_mainwin", "Save settings", None, QtGui.QApplication.UnicodeUTF8))
        self.exitapp.setText(QtGui.QApplication.translate("reco_mainwin", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCreateRecoStandard.setText(QtGui.QApplication.translate("reco_mainwin", "Standard", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCreateRecoPaganin.setText(QtGui.QApplication.translate("reco_mainwin", "With Paganin phase retrieval", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCreateCpr.setText(QtGui.QApplication.translate("reco_mainwin", "Correct projections (flat+dark)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCreateCprLog.setText(QtGui.QApplication.translate("reco_mainwin", "Correct projections with log (standard CT)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCreateFltp.setText(QtGui.QApplication.translate("reco_mainwin", "Paganin phase retrieval", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCreateFltpCpr.setText(QtGui.QApplication.translate("reco_mainwin", "Paganin phase retrieval (+keep corrected projs)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCreateSinosQuick.setText(QtGui.QApplication.translate("reco_mainwin", "Quick sinograms (old prj2sin)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCreateSinosFromTif.setText(QtGui.QApplication.translate("reco_mainwin", "Sinograms from TIF", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCreateSinosFromFltp.setText(QtGui.QApplication.translate("reco_mainwin", "Sinograms from FLTP", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRingRemoval1.setText(QtGui.QApplication.translate("reco_mainwin", "Weak thin rings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRingRemoval2.setText(QtGui.QApplication.translate("reco_mainwin", "Strong thick rings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLoadOnlyPaganin.setText(QtGui.QApplication.translate("reco_mainwin", "Paganin parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLoadOnlyRingRemoval.setText(QtGui.QApplication.translate("reco_mainwin", "Ring removal parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.menuChangeMerlinMountPoint.setText(QtGui.QApplication.translate("reco_mainwin", "Change Merlin mount point", None, QtGui.QApplication.UnicodeUTF8))
        self.menuChangeTargetoX02da.setText(QtGui.QApplication.translate("reco_mainwin", "x02da", None, QtGui.QApplication.UnicodeUTF8))
        self.menuChangeTargetoMerlin.setText(QtGui.QApplication.translate("reco_mainwin", "Merlin", None, QtGui.QApplication.UnicodeUTF8))

